// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IaaS Switch.

package switchapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	iaas "github.com/sacloud/sacloud-sdk-go/api/iaas"
	types "github.com/sacloud/sacloud-sdk-go/api/iaas/types"
	swytch "github.com/sacloud/sacloud-sdk-go/service/iaas/swytch"
)

type Commands struct {
	Find   FindCommand   "cmd:\"\" help:\"スイッチを指定したゾーンで検索して出力します。例: skr iaas-api switch find --zone tk1v\""
	Read   ReadCommand   "cmd:\"\" help:\"スイッチを読み取って出力します。例: skr iaas-api switch read --zone ZONE --id 123456789012\""
	Create CreateCommand "cmd:\"\" help:\"スイッチを作成して出力します。例: skr iaas-api switch create --zone ZONE --name example\""
	Update UpdateCommand "cmd:\"\" help:\"指定項目だけを更新して出力します。例: skr iaas-api switch update --zone ZONE --id 123456789012 --name updated\""
	Delete DeleteCommand "cmd:\"\" help:\"スイッチを削除します。成功時は出力しません。例: skr iaas-api switch delete --zone ZONE --id 123456789012\""
}

type API interface {
	FindWithContext(context.Context, *swytch.FindRequest) ([]*iaas.Switch, error)
	ReadWithContext(context.Context, *swytch.ReadRequest) (*iaas.Switch, error)
	CreateWithContext(context.Context, *swytch.CreateRequest) (*iaas.Switch, error)
	UpdateWithContext(context.Context, *swytch.UpdateRequest) (*iaas.Switch, error)
	DeleteWithContext(context.Context, *swytch.DeleteRequest) error
}

type APIFactory func() (API, error)

type Runtime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *Commands) SetRuntime(runtime Runtime) {
	c.Find.runtime = runtime
	c.Read.runtime = runtime
	c.Create.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
}

func (c *Commands) SetFactory(factory APIFactory) {
	c.Find.factory = factory
	c.Read.factory = factory
	c.Create.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
}

type FindCommand struct {
	Request *string   "help:\"個別フラグと併用不可。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (単一のゾーン名)。任意: Tags は --tags でカンマ区切り、または JSON 配列で指定できます。Count と From は個別フラグ、Names (名前の文字列配列) と Sort (ソートキーの配列) は JSON で指定します。Sort の要素は Key (API のソート対象フィールド名) と Order (0: 昇順、1: 降順) を持つオブジェクトです。有効な Key は対象 API の仕様で確認してください。例: --request='{\\\"Zone\\\":\\\"tk1v\\\",\\\"Names\\\":[\\\"example\\\"]}'。フラグ例: skr iaas-api switch find --zone tk1v --tags production,web\""
	Zone    *string   "name:\"zone\" help:\"必須: 対象ゾーン名。例: --zone tk1v\""
	Tags    *[]string "name:\"tags\" help:\"任意: タグの配列。カンマ区切りで指定します。API の Tags フィールドに対応します。\" sep:\",\""
	Count   *int      "name:\"count\" help:\"任意: 取得件数 (整数)。\""
	From    *int      "name:\"from\" help:\"任意: 取得開始位置 (整数)。\""
	factory APIFactory
	runtime Runtime
}

func (c *FindCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Zone != nil
	flagsSet = flagsSet || c.Tags != nil
	flagsSet = flagsSet || c.Count != nil
	flagsSet = flagsSet || c.From != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &swytch.FindRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Zone == nil {
			return fmt.Errorf("--zone が必要です")
		}
		if c.Zone != nil {
			request.Zone = *c.Zone
		}
		if c.Tags != nil {
			value := types.Tags(*c.Tags)
			request.Tags = value
		}
		if c.Count != nil {
			request.Count = *c.Count
		}
		if c.From != nil {
			request.From = *c.From
		}
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateSwitchFindRequest", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.FindWithContext(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ReadCommand struct {
	Request *string "help:\"個別フラグと併用不可。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (ゾーン名)、ID (作成結果にある数値)。例: --request='{\\\"Zone\\\":\\\"tk1v\\\",\\\"ID\\\":123456789012}'。ID は実際の値に置き換えます。\""
	Zone    *string "name:\"zone\" help:\"必須: 対象ゾーン名。\""
	ID      *int64  "name:\"id\" help:\"必須: 作成結果の ID (数値)。\""
	factory APIFactory
	runtime Runtime
}

func (c *ReadCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Zone != nil
	flagsSet = flagsSet || c.ID != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &swytch.ReadRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Zone == nil {
			return fmt.Errorf("--zone が必要です")
		}
		if c.Zone != nil {
			request.Zone = *c.Zone
		}
		if c.ID == nil {
			return fmt.Errorf("--id が必要です")
		}
		if c.ID != nil {
			value := types.ID(*c.ID)
			request.ID = value
		}
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateSwitchReadRequest", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadWithContext(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type CreateCommand struct {
	Request        *string   "help:\"個別フラグと併用不可。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (ゾーン名)、Name (名前)。任意: Description (説明、最大512文字)、Tags (--tags でカンマ区切り、JSON 経路では文字列配列)、IconID (数値)、NetworkMaskLen (整数)、DefaultRoute (文字列)。JSON 例: {\\\"Zone\\\":\\\"tk1v\\\",\\\"Name\\\":\\\"example\\\",\\\"Tags\\\":[\\\"test\\\"]}。フラグ例: skr iaas-api switch create --zone tk1v --name example --tags production,web\""
	Zone           *string   "name:\"zone\" help:\"必須: 作成先のゾーン名。\""
	Name           *string   "name:\"name\" help:\"必須: スイッチの名前。\""
	Tags           *[]string "name:\"tags\" help:\"任意: タグの配列。カンマ区切りで指定します。API の Tags フィールドに対応します。\" sep:\",\""
	Description    *string   "name:\"description\" help:\"任意: 説明 (最大512文字)。\""
	IconID         *int64    "name:\"icon-id\" help:\"任意: アイコンの ID (数値)。\""
	NetworkMaskLen *int      "name:\"network-mask-len\" help:\"任意: ネットワークマスク長 (整数)。\""
	DefaultRoute   *string   "name:\"default-route\" help:\"任意: デフォルトルート (文字列)。\""
	factory        APIFactory
	runtime        Runtime
}

func (c *CreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Zone != nil
	flagsSet = flagsSet || c.Name != nil
	flagsSet = flagsSet || c.Tags != nil
	flagsSet = flagsSet || c.Description != nil
	flagsSet = flagsSet || c.IconID != nil
	flagsSet = flagsSet || c.NetworkMaskLen != nil
	flagsSet = flagsSet || c.DefaultRoute != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &swytch.CreateRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Zone == nil {
			return fmt.Errorf("--zone が必要です")
		}
		if c.Zone != nil {
			request.Zone = *c.Zone
		}
		if c.Name == nil {
			return fmt.Errorf("--name が必要です")
		}
		if c.Name != nil {
			request.Name = *c.Name
		}
		if c.Tags != nil {
			value := types.Tags(*c.Tags)
			request.Tags = value
		}
		if c.Description != nil {
			request.Description = *c.Description
		}
		if c.IconID != nil {
			value := types.ID(*c.IconID)
			request.IconID = value
		}
		if c.NetworkMaskLen != nil {
			request.NetworkMaskLen = *c.NetworkMaskLen
		}
		if c.DefaultRoute != nil {
			request.DefaultRoute = *c.DefaultRoute
		}
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateSwitchCreateRequest", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.CreateWithContext(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type UpdateCommand struct {
	Request        *string   "help:\"個別フラグと併用不可。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (ゾーン名)、ID (数値)。任意: Name (名前)、Description (説明、最大512文字)、Tags (--tags でカンマ区切り、JSON 経路では文字列配列)、IconID (数値)、NetworkMaskLen (整数)、DefaultRoute (文字列)。省略した項目は変更しません。JSON 例: {\\\"Zone\\\":\\\"tk1v\\\",\\\"ID\\\":123456789012,\\\"Tags\\\":[\\\"test\\\"]}。フラグ例: skr iaas-api switch update --zone tk1v --id 123456789012 --tags production,web。ID は実際の値に置き換えます。\""
	Zone           *string   "name:\"zone\" help:\"必須: 対象ゾーン名。\""
	ID             *int64    "name:\"id\" help:\"必須: 更新対象の ID (数値)。\""
	Tags           *[]string "name:\"tags\" help:\"任意: 更新後のタグ配列。カンマ区切りで指定します。未指定なら変更しません。\" sep:\",\""
	Name           *string   "name:\"name\" help:\"任意: 新しい名前。未指定なら変更しません。\""
	Description    *string   "name:\"description\" help:\"任意: 新しい説明 (最大512文字)。空文字列も指定できます。\""
	IconID         *int64    "name:\"icon-id\" help:\"任意: アイコンの ID (数値)。\""
	NetworkMaskLen *int      "name:\"network-mask-len\" help:\"任意: ネットワークマスク長 (整数)。0 も明示できます。\""
	DefaultRoute   *string   "name:\"default-route\" help:\"任意: デフォルトルート (文字列)。空文字列も指定できます。\""
	factory        APIFactory
	runtime        Runtime
}

func (c *UpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Zone != nil
	flagsSet = flagsSet || c.ID != nil
	flagsSet = flagsSet || c.Tags != nil
	flagsSet = flagsSet || c.Name != nil
	flagsSet = flagsSet || c.Description != nil
	flagsSet = flagsSet || c.IconID != nil
	flagsSet = flagsSet || c.NetworkMaskLen != nil
	flagsSet = flagsSet || c.DefaultRoute != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &swytch.UpdateRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Zone == nil {
			return fmt.Errorf("--zone が必要です")
		}
		if c.Zone != nil {
			request.Zone = *c.Zone
		}
		if c.ID == nil {
			return fmt.Errorf("--id が必要です")
		}
		if c.ID != nil {
			value := types.ID(*c.ID)
			request.ID = value
		}
		if c.Tags != nil {
			value := types.Tags(*c.Tags)
			request.Tags = &value
		}
		if c.Name != nil {
			request.Name = c.Name
		}
		if c.Description != nil {
			request.Description = c.Description
		}
		if c.IconID != nil {
			value := types.ID(*c.IconID)
			request.IconID = &value
		}
		if c.NetworkMaskLen != nil {
			request.NetworkMaskLen = c.NetworkMaskLen
		}
		if c.DefaultRoute != nil {
			request.DefaultRoute = c.DefaultRoute
		}
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateSwitchUpdateRequest", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateWithContext(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type DeleteCommand struct {
	Request               *string "help:\"個別フラグと併用不可。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (ゾーン名)、ID (数値)。任意: FailIfNotFound (真偽値)、WaitForRelease (真偽値)、WaitForReleaseTimeout (秒の整数)、WaitForReleaseTick (秒の整数)。例: --request='{\\\"Zone\\\":\\\"tk1v\\\",\\\"ID\\\":123456789012,\\\"FailIfNotFound\\\":true}'。ID は実際の値に置き換えます。\""
	Zone                  *string "name:\"zone\" help:\"必須: 対象ゾーン名。\""
	ID                    *int64  "name:\"id\" help:\"必須: 削除対象の ID (数値)。\""
	FailIfNotFound        *bool   "name:\"fail-if-not-found\" help:\"任意: 対象が見つからない場合にエラーにします (真偽値)。\""
	WaitForRelease        *bool   "name:\"wait-for-release\" help:\"任意: 他リソースから参照されている間は削除を待ちます (真偽値)。\""
	WaitForReleaseTimeout *int    "name:\"wait-for-release-timeout\" help:\"任意: 待機のタイムアウト (秒の整数、既定3600秒)。\""
	WaitForReleaseTick    *int    "name:\"wait-for-release-tick\" help:\"任意: 待機時の確認間隔 (秒の整数、既定5秒)。\""
	factory               APIFactory
	runtime               Runtime
}

func (c *DeleteCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Zone != nil
	flagsSet = flagsSet || c.ID != nil
	flagsSet = flagsSet || c.FailIfNotFound != nil
	flagsSet = flagsSet || c.WaitForRelease != nil
	flagsSet = flagsSet || c.WaitForReleaseTimeout != nil
	flagsSet = flagsSet || c.WaitForReleaseTick != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &swytch.DeleteRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Zone == nil {
			return fmt.Errorf("--zone が必要です")
		}
		if c.Zone != nil {
			request.Zone = *c.Zone
		}
		if c.ID == nil {
			return fmt.Errorf("--id が必要です")
		}
		if c.ID != nil {
			value := types.ID(*c.ID)
			request.ID = value
		}
		if c.FailIfNotFound != nil {
			request.FailIfNotFound = *c.FailIfNotFound
		}
		if c.WaitForRelease != nil {
			request.WaitForRelease = *c.WaitForRelease
		}
		if c.WaitForReleaseTimeout != nil {
			request.WaitForReleaseTimeout = *c.WaitForReleaseTimeout
		}
		if c.WaitForReleaseTick != nil {
			request.WaitForReleaseTick = *c.WaitForReleaseTick
		}
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateSwitchDeleteRequest", request); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.DeleteWithContext(context.Background(), request)
}
