// Copyright 2022-2026 The sacloud/skr Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package apigen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

type Config struct {
	Package     string            `json:"package"`
	Resource    string            `json:"resource"`
	CommandType string            `json:"command_type"`
	APIType     string            `json:"api_type"`
	FactoryType string            `json:"factory_type"`
	RuntimeType string            `json:"runtime_type"`
	Imports     map[string]string `json:"imports"`
	Operations  []Operation       `json:"operations"`
}

type Operation struct {
	Name             string      `json:"name"`
	CommandType      string      `json:"command_type"`
	Help             string      `json:"help"`
	Method           string      `json:"method"`
	RequestType      string      `json:"request_type,omitempty"`
	ResponseType     string      `json:"response_type,omitempty"`
	RequestHelp      string      `json:"request_help,omitempty"`
	RequestValidator string      `json:"request_validator,omitempty"`
	Handwritten      bool        `json:"handwritten,omitempty"`
	ZoneSearch       *ZoneSearch `json:"zone_search,omitempty"`
	Flags            []Flag      `json:"flags,omitempty"`
}

type ZoneSearch struct {
	FlagField    string `json:"flag_field"`
	RequestField string `json:"request_field"`
}

type Flag struct {
	Name       string `json:"name"`
	Field      string `json:"field"`
	Type       string `json:"type"`
	Help       string `json:"help"`
	Required   bool   `json:"required,omitempty"`
	Pointer    bool   `json:"pointer,omitempty"`
	Conversion string `json:"conversion,omitempty"`
}

type importSpec struct {
	Alias string
	Path  string
}

type templateConfig struct {
	Config
	Imports       []importSpec
	Operations    []templateOperation
	HasZoneSearch bool
}

type templateOperation struct {
	Operation
	ZoneSearchItemType string
}

const sourceTemplate = `// Code generated by cmd/apigen-iaas; DO NOT EDIT.
// API resource: {{.Resource}}.

package {{.Package}}

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
{{- if .HasZoneSearch }}
	zones "github.com/sacloud/skr/internal/iaas/zones"
{{- end }}
{{- range .Imports }}
	{{.Alias}} {{printf "%q" .Path}}
{{- end }}
)

type {{.CommandType}} struct {
{{- range .Operations }}
	{{.Name}} {{.CommandType}} {{commandTag .Help}}
{{- end }}
}

type {{.APIType}} interface {
{{- range .Operations }}
	{{.Method}}({{if .RequestType}}context.Context, *{{.RequestType}}{{else}}context.Context{{end}}) {{if .ResponseType}}({{.ResponseType}}, error){{else}}error{{end}}
{{- end }}
}

type {{.FactoryType}} func() ({{.APIType}}, error)

type {{.RuntimeType}} struct {
	DecodeRequest func(string, any) error
	OutputType func(*kong.Context) (string, error)
	WriteOutput func(*kong.Context, string, any, ...[]string) error
	ValidateRequest func(string, any) error
}

func (c *{{.CommandType}}) SetRuntime(runtime {{.RuntimeType}}) {
{{- range .Operations }}
{{- if not .Handwritten }}
	c.{{.Name}}.runtime = runtime
{{- end }}
{{- end }}
}

func (c *{{.CommandType}}) SetFactory(factory {{.FactoryType}}) {
{{- range .Operations }}
	c.{{.Name}}.factory = factory
{{- end }}
}
{{- if .HasZoneSearch }}

func (c *{{.CommandType}}) SetZoneFactory(factory zones.Factory) {
{{- range .Operations }}
{{- if .ZoneSearch }}
	c.{{.Name}}.zoneFactory = factory
{{- end }}
{{- end }}
}
{{- end }}

{{range .Operations}}
{{- if not .Handwritten }}
type {{.CommandType}} struct {
{{- if .RequestType }}
	Request *string {{if .RequestHelp}}{{helpTag .RequestHelp}}{{else}}{{helpTag "API リクエスト JSON を直接または @path.json で指定します。個別フラグと併用できません。"}}{{end}}
{{- range .Flags }}
	{{.Field}} *{{.Type}} {{flagTag .Name .Help}}
{{- end }}
{{- end }}
{{- if .ZoneSearch }}
	zoneFactory zones.Factory
{{- end }}
	factory {{$.FactoryType}}
	runtime {{$.RuntimeType}}
}

func (c *{{.CommandType}}) Run(ctx *kong.Context) error {
{{- if .RequestType }}
	flagsSet := false
{{- range .Flags }}
	flagsSet = flagsSet || c.{{.Field}} != nil
{{- end }}
	if c.Request != nil && flagsSet {
	return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &{{.RequestType}}{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
{{- if .Flags }}
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
{{- else }}
		return fmt.Errorf("--request が必要です")
{{- end }}
{{- range .Flags }}
{{- if .Required }}
		if c.{{.Field}} == nil {
			return fmt.Errorf("--{{.Name}} が必要です")
		}
{{- end }}
		if c.{{.Field}} != nil {
{{- if .Conversion }}
			value := {{.Conversion}}(*c.{{.Field}})
{{- if .Pointer }}
			request.{{.Field}} = &value
{{- else }}
			request.{{.Field}} = value
{{- end }}
{{- else if .Pointer }}
			request.{{.Field}} = c.{{.Field}}
{{- else }}
			request.{{.Field}} = *c.{{.Field}}
{{- end }}
		}
{{- end }}
	}
{{- if .RequestValidator }}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("{{.RequestValidator}}", request); err != nil {
		return err
	}
{{- end }}
{{- end }}
{{- if .ResponseType }}
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
	return err
	}
{{- end }}
	if c.factory == nil {
	return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
	return err
	}
{{- if .ZoneSearch }}
	if c.Request == nil && c.{{.ZoneSearch.FlagField}} != nil && *c.{{.ZoneSearch.FlagField}} == zones.All {
		var tableZones []string
		result, err := zones.FindInAll(context.Background(), c.zoneFactory, func(ctx context.Context, zone string) ([]{{.ZoneSearchItemType}}, error) {
			zoneRequest := *request
			zoneRequest.{{.ZoneSearch.RequestField}} = zone
			items, err := op.{{.Method}}(ctx, &zoneRequest)
			if err != nil {
				return nil, err
			}
			for range items {
				tableZones = append(tableZones, zone)
			}
			return items, nil
		})
		if err != nil {
			return err
		}
		if c.runtime.WriteOutput == nil {
			return fmt.Errorf("API 出力処理が設定されていません")
		}
		return c.runtime.WriteOutput(ctx, format, result, tableZones)
	}
{{- end }}
{{- if .ResponseType }}
{{- if .RequestType }}
	result, err := op.{{.Method}}(context.Background(), request)
{{- else }}
	result, err := op.{{.Method}}(context.Background())
{{- end }}
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
{{- else }}
{{- if .RequestType }}
	return op.{{.Method}}(context.Background(), request)
{{- else }}
	return op.{{.Method}}(context.Background())
{{- end }}
{{- end }}
}
{{- end }}
{{end}}`

func DecodeConfig(data []byte) (Config, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var config Config
	if err := decoder.Decode(&config); err != nil {
		return Config{}, fmt.Errorf("decode generator config: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil {
			return Config{}, fmt.Errorf("decode generator config: multiple JSON values")
		}
		return Config{}, fmt.Errorf("decode generator config: trailing data: %w", err)
	}
	if err := config.Validate(); err != nil {
		return Config{}, err
	}
	return config, nil
}

func (c Config) Validate() error {
	if !token.IsIdentifier(c.Package) || token.Lookup(c.Package).IsKeyword() {
		return fmt.Errorf("package must be a valid Go identifier")
	}
	for label, name := range map[string]string{
		"command_type": c.CommandType, "api_type": c.APIType,
		"factory_type": c.FactoryType, "runtime_type": c.RuntimeType,
	} {
		if !token.IsIdentifier(name) || token.Lookup(name).IsKeyword() {
			return fmt.Errorf("%s must be a valid Go identifier", label)
		}
	}
	if strings.TrimSpace(c.Resource) == "" {
		return fmt.Errorf("resource must not be empty")
	}
	if len(c.Operations) == 0 {
		return fmt.Errorf("at least one operation is required")
	}

	aliases := map[string]bool{"context": true, "fmt": true, "kong": true}
	for alias, path := range c.Imports {
		if !token.IsIdentifier(alias) || token.Lookup(alias).IsKeyword() || aliases[alias] {
			return fmt.Errorf("invalid or reserved import alias %q", alias)
		}
		if strings.TrimSpace(path) == "" {
			return fmt.Errorf("import path for alias %q must not be empty", alias)
		}
		aliases[alias] = true
	}

	operations := make(map[string]bool, len(c.Operations))
	methods := make(map[string]bool, len(c.Operations))
	commandTypes := map[string]bool{c.CommandType: true, c.APIType: true, c.FactoryType: true}
	for i, operation := range c.Operations {
		if !token.IsIdentifier(operation.Name) || token.Lookup(operation.Name).IsKeyword() {
			return fmt.Errorf("operation %d name must be a valid Go identifier", i)
		}
		if !token.IsIdentifier(operation.CommandType) || token.Lookup(operation.CommandType).IsKeyword() {
			return fmt.Errorf("operation %q command_type must be a valid Go identifier", operation.Name)
		}
		if operations[operation.Name] {
			return fmt.Errorf("duplicate operation name %q", operation.Name)
		}
		if commandTypes[operation.CommandType] {
			return fmt.Errorf("duplicate generated type name %q", operation.CommandType)
		}
		if !token.IsIdentifier(operation.Method) || token.Lookup(operation.Method).IsKeyword() {
			return fmt.Errorf("operation %q method must be a valid Go identifier", operation.Name)
		}
		if methods[operation.Method] {
			return fmt.Errorf("duplicate SDK method %q", operation.Method)
		}
		if strings.TrimSpace(operation.Help) == "" {
			return fmt.Errorf("operation %q help must not be empty", operation.Name)
		}
		if err := validateType(operation.RequestType); err != nil {
			return fmt.Errorf("operation %q request_type: %w", operation.Name, err)
		}
		if err := validateType(operation.ResponseType); err != nil {
			return fmt.Errorf("operation %q response_type: %w", operation.Name, err)
		}
		if operation.RequestValidator != "" &&
			(!token.IsIdentifier(operation.RequestValidator) || token.Lookup(operation.RequestValidator).IsKeyword()) {
			return fmt.Errorf("operation %q request_validator must be a valid Go identifier", operation.Name)
		}
		if operation.RequestValidator != "" && (operation.RequestType == "" || operation.Handwritten) {
			return fmt.Errorf("operation %q request_validator requires a generated request operation", operation.Name)
		}
		if operation.RequestType == "" && len(operation.Flags) > 0 {
			return fmt.Errorf("operation %q cannot define flags without request_type", operation.Name)
		}
		if operation.Handwritten && len(operation.Flags) > 0 {
			return fmt.Errorf("handwritten operation %q cannot define generated flags", operation.Name)
		}
		flagNames := make(map[string]bool, len(operation.Flags))
		fields := make(map[string]bool, len(operation.Flags))
		for _, flag := range operation.Flags {
			if !isKebabName(flag.Name) {
				return fmt.Errorf("operation %q flag name %q must be kebab-case", operation.Name, flag.Name)
			}
			if !token.IsIdentifier(flag.Field) || token.Lookup(flag.Field).IsKeyword() {
				return fmt.Errorf("operation %q flag field %q must be a valid Go identifier", operation.Name, flag.Field)
			}
			if flagNames[flag.Name] || fields[flag.Field] {
				return fmt.Errorf("operation %q has duplicate flag name or field", operation.Name)
			}
			flagNames[flag.Name] = true
			fields[flag.Field] = true
			switch flag.Type {
			case "string", "bool", "int", "int64":
			default:
				return fmt.Errorf("operation %q flag %q has unsupported type %q", operation.Name, flag.Name, flag.Type)
			}
			if strings.TrimSpace(flag.Help) == "" {
				return fmt.Errorf("operation %q flag %q help must not be empty", operation.Name, flag.Name)
			}
			if err := validateType(flag.Conversion); err != nil {
				return fmt.Errorf("operation %q flag %q conversion: %w", operation.Name, flag.Name, err)
			}
			if flag.Conversion != "" && flag.Pointer && strings.HasPrefix(flag.Conversion, "*") {
				return fmt.Errorf("operation %q flag %q pointer conversion must name a value type", operation.Name, flag.Name)
			}
		}
		if operation.ZoneSearch != nil {
			if operation.Handwritten {
				return fmt.Errorf("operation %q cannot combine handwritten with zone_search", operation.Name)
			}
			if operation.RequestType == "" || operation.ResponseType == "" {
				return fmt.Errorf("operation %q zone_search requires request_type and response_type", operation.Name)
			}
			if !token.IsIdentifier(operation.ZoneSearch.FlagField) || token.Lookup(operation.ZoneSearch.FlagField).IsKeyword() ||
				!token.IsIdentifier(operation.ZoneSearch.RequestField) || token.Lookup(operation.ZoneSearch.RequestField).IsKeyword() {
				return fmt.Errorf("operation %q zone_search fields must be valid Go identifiers", operation.Name)
			}
			zoneFlagFound := false
			for _, flag := range operation.Flags {
				if flag.Field == operation.ZoneSearch.FlagField && flag.Type == "string" && flag.Required {
					zoneFlagFound = true
					break
				}
			}
			if !zoneFlagFound {
				return fmt.Errorf("operation %q zone_search requires a required string flag for %q", operation.Name, operation.ZoneSearch.FlagField)
			}
			if _, err := responseSliceElement(operation.ResponseType); err != nil {
				return fmt.Errorf("operation %q zone_search response_type: %w", operation.Name, err)
			}
		}
		operations[operation.Name] = true
		methods[operation.Method] = true
		commandTypes[operation.CommandType] = true
	}
	return nil
}

func validateType(value string) error {
	if value == "" {
		return nil
	}
	if _, err := parser.ParseExpr(value); err != nil {
		return fmt.Errorf("invalid Go type %q: %w", value, err)
	}
	return nil
}

func responseSliceElement(value string) (string, error) {
	expression, err := parser.ParseExpr(value)
	if err != nil {
		return "", err
	}
	array, ok := expression.(*ast.ArrayType)
	if !ok || array.Len != nil {
		return "", fmt.Errorf("must be a slice type")
	}
	var element bytes.Buffer
	if err := format.Node(&element, token.NewFileSet(), array.Elt); err != nil {
		return "", err
	}
	return element.String(), nil
}

func isKebabName(value string) bool {
	if value == "" || strings.HasPrefix(value, "-") || strings.HasSuffix(value, "-") || strings.Contains(value, "--") {
		return false
	}
	for _, r := range value {
		if r != '-' && (r < 'a' || r > 'z') && (r < '0' || r > '9') {
			return false
		}
	}
	return true
}

func Generate(config Config) ([]byte, error) {
	if err := config.Validate(); err != nil {
		return nil, err
	}
	imports := make([]importSpec, 0, len(config.Imports))
	for alias, path := range config.Imports {
		imports = append(imports, importSpec{Alias: alias, Path: path})
	}
	sort.Slice(imports, func(i, j int) bool { return imports[i].Alias < imports[j].Alias })
	operations := make([]templateOperation, 0, len(config.Operations))
	hasZoneSearch := false
	for _, operation := range config.Operations {
		item := templateOperation{Operation: operation}
		if operation.ZoneSearch != nil {
			item.ZoneSearchItemType, _ = responseSliceElement(operation.ResponseType)
			hasZoneSearch = true
		}
		operations = append(operations, item)
	}

	tmpl, err := template.New("api").Funcs(template.FuncMap{
		"commandTag": func(help string) string {
			return strconv.Quote("cmd:\"\" help:" + strconv.Quote(help))
		},
		"flagTag": func(name, help string) string {
			return strconv.Quote("name:" + strconv.Quote(name) + " help:" + strconv.Quote(help))
		},
		"helpTag": func(help string) string {
			return strconv.Quote("help:" + strconv.Quote(help))
		},
	}).Parse(sourceTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse source template: %w", err)
	}
	var source bytes.Buffer
	if err := tmpl.Execute(&source, templateConfig{
		Config: config, Imports: imports, Operations: operations, HasZoneSearch: hasZoneSearch,
	}); err != nil {
		return nil, fmt.Errorf("render source: %w", err)
	}
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}
