// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IaaS Disk.

package diskapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	iaas "github.com/sacloud/sacloud-sdk-go/api/iaas"
	types "github.com/sacloud/sacloud-sdk-go/api/iaas/types"
	disk "github.com/sacloud/sacloud-sdk-go/service/iaas/disk"
	zones "github.com/sacloud/skr/internal/iaas/zones"
)

type Commands struct {
	Find   FindCommand   "cmd:\"\" help:\"ディスクを検索して出力します。--zone all で全ゾーンを検索し、--count と --from は各ゾーンの検索に適用します。例: skr iaas-api disk find --zone ZONE\""
	Read   ReadCommand   "cmd:\"\" help:\"ディスクを読み取って出力します。例: skr iaas-api disk read --zone ZONE --id 123456789012\""
	Create CreateCommand "cmd:\"\" help:\"JSON リクエストでディスクを作成して出力します。ディスクプラン、接続インターフェース、サイズを対象ゾーンに合わせて指定してください。例: skr iaas-api disk create --request @disk-create.json\""
	Update UpdateCommand "cmd:\"\" help:\"JSON リクエストでディスクの指定項目を更新して出力します。省略した項目は変更しません。例: skr iaas-api disk update --request @disk-update.json\""
	Delete DeleteCommand "cmd:\"\" help:\"ディスクを削除します。サーバに接続中のディスクは削除できません。削除後は復旧できません。成功時は出力しません。例: skr iaas-api disk delete --zone ZONE --id 123456789012 --fail-if-not-found\""
}

type API interface {
	FindWithContext(context.Context, *disk.FindRequest) ([]*iaas.Disk, error)
	ReadWithContext(context.Context, *disk.ReadRequest) (*iaas.Disk, error)
	CreateWithContext(context.Context, *disk.CreateRequest) (*iaas.Disk, error)
	UpdateWithContext(context.Context, *disk.UpdateRequest) (*iaas.Disk, error)
	DeleteWithContext(context.Context, *disk.DeleteRequest) error
}

type APIFactory func() (API, error)

type Runtime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *Commands) SetRuntime(runtime Runtime) {
	c.Find.runtime = runtime
	c.Read.runtime = runtime
	c.Create.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
}

func (c *Commands) SetFactory(factory APIFactory) {
	c.Find.factory = factory
	c.Read.factory = factory
	c.Create.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
}

func (c *Commands) SetZoneFactory(factory zones.Factory) {
	c.Find.zoneFactory = factory
}

type FindCommand struct {
	Request     *string "help:\"個別フラグと併用不可。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (単一ゾーン名)。任意: Names (名前の文字列配列)、Tags (タグの文字列配列)、Sort (ソートキーの配列)、Count (取得件数)、From (開始位置)。配列条件は JSON で指定します。例: --request='{\\\"Zone\\\":\\\"ZONE\\\",\\\"Names\\\":[\\\"example\\\"]}'\""
	Zone        *string "name:\"zone\" help:\"必須: 対象ゾーン名。all を指定すると全ゾーンを検索します。JSON の --request では全ゾーン検索になりません。\""
	Count       *int    "name:\"count\" help:\"任意: 取得件数 (整数)。\""
	From        *int    "name:\"from\" help:\"任意: 取得開始位置 (整数)。\""
	zoneFactory zones.Factory
	factory     APIFactory
	runtime     Runtime
}

func (c *FindCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Zone != nil
	flagsSet = flagsSet || c.Count != nil
	flagsSet = flagsSet || c.From != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &disk.FindRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Zone == nil {
			return fmt.Errorf("--zone が必要です")
		}
		if c.Zone != nil {
			request.Zone = *c.Zone
		}
		if c.Count != nil {
			request.Count = *c.Count
		}
		if c.From != nil {
			request.From = *c.From
		}
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateDiskFindRequest", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	if c.Request == nil && c.Zone != nil && *c.Zone == zones.All {
		result, err := zones.FindInAll(context.Background(), c.zoneFactory, func(ctx context.Context, zone string) ([]*iaas.Disk, error) {
			zoneRequest := *request
			zoneRequest.Zone = zone
			items, err := op.FindWithContext(ctx, &zoneRequest)
			if err != nil {
				return nil, err
			}
			return items, nil
		})
		if err != nil {
			return err
		}
		if c.runtime.WriteOutput == nil {
			return fmt.Errorf("API 出力処理が設定されていません")
		}
		return c.runtime.WriteOutput(ctx, result)
	}
	result, err := op.FindWithContext(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ReadCommand struct {
	Request *string "help:\"個別フラグと併用不可。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (ゾーン名)、ID (数値)。例: --request='{\\\"Zone\\\":\\\"ZONE\\\",\\\"ID\\\":123456789012}'。ID は実際の値に置き換えます。\""
	Zone    *string "name:\"zone\" help:\"必須: 対象ゾーン名。\""
	ID      *int64  "name:\"id\" help:\"必須: ディスク ID (数値)。\""
	factory APIFactory
	runtime Runtime
}

func (c *ReadCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Zone != nil
	flagsSet = flagsSet || c.ID != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &disk.ReadRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Zone == nil {
			return fmt.Errorf("--zone が必要です")
		}
		if c.Zone != nil {
			request.Zone = *c.Zone
		}
		if c.ID == nil {
			return fmt.Errorf("--id が必要です")
		}
		if c.ID != nil {
			value := types.ID(*c.ID)
			request.ID = value
		}
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateDiskReadRequest", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadWithContext(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type CreateCommand struct {
	Request *string "help:\"JSON 専用です。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (ゾーン名)、Name (名前)、DiskPlanID (対象ゾーンで利用できるディスクプラン ID)、Connection (IDE または virtio)、SizeGB (プランとゾーンで利用できるサイズ、GB)。任意: Description、Tags、IconID、EncryptionAlgorithm、KMSKeyID、DedicatedStorageContractID、SourceDiskID、SourceArchiveID、ServerID、DistantFrom、OSType、EditParameter、NoWait。ディスクやアーカイブをコピーする場合は対応する ID を指定します。作成先のゾーン、プラン、サイズ、接続先は事前に確認してください。例: --request @disk-create.json。JSON 例: {\\\"Zone\\\":\\\"ZONE\\\",\\\"Name\\\":\\\"DISK-NAME\\\",\\\"DiskPlanID\\\":4,\\\"Connection\\\":\\\"virtio\\\",\\\"SizeGB\\\":20}。DiskPlanID と SizeGB は対象プランに合わせて置き換えてください。\""
	factory APIFactory
	runtime Runtime
}

func (c *CreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &disk.CreateRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateDiskCreateRequest", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.CreateWithContext(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type UpdateCommand struct {
	Request *string "help:\"JSON 専用です。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (ゾーン名)、ID (数値)、変更する項目を1つ以上。変更可能な項目: Name、Description、Tags、IconID、Connection、EditParameter。省略した項目は変更しません。例: --request='{\\\"Zone\\\":\\\"ZONE\\\",\\\"ID\\\":123456789012,\\\"Name\\\":\\\"UPDATED-DISK-NAME\\\"}'。Zone、ID、Name は実際の値に置き換えます。\""
	factory APIFactory
	runtime Runtime
}

func (c *UpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &disk.UpdateRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateDiskUpdateRequest", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateWithContext(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type DeleteCommand struct {
	Request               *string "help:\"個別フラグと併用不可。JSON オブジェクトを直接または @path.json で指定します。必須: Zone (ゾーン名)、ID (数値)。任意: FailIfNotFound (対象がない場合にエラー)、WaitForRelease (他リソースから参照されている間の削除待機)、WaitForReleaseTimeout (秒)、WaitForReleaseTick (秒)。サーバ接続中のディスクは削除できません。削除後は復旧できないため、対象 ID と接続状態を確認してください。例: --request='{\\\"Zone\\\":\\\"ZONE\\\",\\\"ID\\\":123456789012,\\\"FailIfNotFound\\\":true}'。ID は実際の値に置き換えます。\""
	Zone                  *string "name:\"zone\" help:\"必須: 対象ゾーン名。\""
	ID                    *int64  "name:\"id\" help:\"必須: 削除対象のディスク ID (数値)。\""
	FailIfNotFound        *bool   "name:\"fail-if-not-found\" help:\"任意: 対象ディスクが見つからない場合にエラーにします。\""
	WaitForRelease        *bool   "name:\"wait-for-release\" help:\"任意: 他リソースから参照されている間は削除を待ちます。\""
	WaitForReleaseTimeout *int    "name:\"wait-for-release-timeout\" help:\"任意: 削除待機のタイムアウト (秒)。\""
	WaitForReleaseTick    *int    "name:\"wait-for-release-tick\" help:\"任意: 削除待機中の確認間隔 (秒)。\""
	factory               APIFactory
	runtime               Runtime
}

func (c *DeleteCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Zone != nil
	flagsSet = flagsSet || c.ID != nil
	flagsSet = flagsSet || c.FailIfNotFound != nil
	flagsSet = flagsSet || c.WaitForRelease != nil
	flagsSet = flagsSet || c.WaitForReleaseTimeout != nil
	flagsSet = flagsSet || c.WaitForReleaseTick != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &disk.DeleteRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Zone == nil {
			return fmt.Errorf("--zone が必要です")
		}
		if c.Zone != nil {
			request.Zone = *c.Zone
		}
		if c.ID == nil {
			return fmt.Errorf("--id が必要です")
		}
		if c.ID != nil {
			value := types.ID(*c.ID)
			request.ID = value
		}
		if c.FailIfNotFound != nil {
			request.FailIfNotFound = *c.FailIfNotFound
		}
		if c.WaitForRelease != nil {
			request.WaitForRelease = *c.WaitForRelease
		}
		if c.WaitForReleaseTimeout != nil {
			request.WaitForReleaseTimeout = *c.WaitForReleaseTimeout
		}
		if c.WaitForReleaseTick != nil {
			request.WaitForReleaseTick = *c.WaitForReleaseTick
		}
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("validateDiskDeleteRequest", request); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.DeleteWithContext(context.Background(), request)
}
