// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM role.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type IAMRoleCommands struct {
	List IAMRoleListCommand "cmd:\"\" help:\"利用可能な IAM ロールを一覧表示します。\""
	Read IAMRoleReadCommand "cmd:\"\" help:\"ID を指定して IAM ロールを読み取ります。\""
}

type IAMRoleAPI interface {
	List(context.Context, *int, *int) (*v1.ListIamRolesOK, error)
	Read(context.Context, string) (*v1.IamRole, error)
}

type IAMRoleAPIFactory func() (IAMRoleAPI, error)

type IAMRoleRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *IAMRoleCommands) SetRuntime(runtime IAMRoleRuntime) {
	c.List.runtime = runtime
	c.Read.runtime = runtime
}

func (c *IAMRoleCommands) SetFactory(factory IAMRoleAPIFactory) {
	c.List.factory = factory
	c.Read.factory = factory
}

type IAMRoleListCommand struct {
	Page    *int "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage *int "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	factory IAMRoleAPIFactory
	runtime IAMRoleRuntime
}

func (c *IAMRoleListCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background(), c.Page, c.PerPage)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type IAMRoleReadCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"読み取る IAM ロール ID。\""
	factory IAMRoleAPIFactory
	runtime IAMRoleRuntime
}

func (c *IAMRoleReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
