// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM project.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	project "github.com/sacloud/sacloud-sdk-go/api/iam/apis/project"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type ProjectCommands struct {
	List   ProjectListCommand   "cmd:\"\" help:\"IAM プロジェクトを一覧表示します。\""
	Create ProjectCreateCommand "cmd:\"\" help:\"IAM プロジェクトを作成します。既存のフォルダ内に作成する場合は --parent-folder-id を指定してください。\""
	Read   ProjectReadCommand   "cmd:\"\" help:\"ID を指定して IAM プロジェクトを読み取ります。\""
	Update ProjectUpdateCommand "cmd:\"\" help:\"IAM プロジェクトの名前と説明を更新します。両方の値を指定してください。\""
	Move   ProjectMoveCommand   "cmd:\"\" help:\"指定したプロジェクトをフォルダへ移動します。\""
	Delete ProjectDeleteCommand "cmd:\"\" help:\"ID を指定して IAM プロジェクトを削除します。\""
}

type ProjectAPI interface {
	List(context.Context, project.ListParams) (*v1.ListProjectsOK, error)
	Create(context.Context, project.CreateParams) (*v1.Project, error)
	Read(context.Context, int) (*v1.Project, error)
	Update(context.Context, int, string, string) (*v1.Project, error)
	Move(context.Context, []int, *int) error
	Delete(context.Context, int) error
}

type ProjectAPIFactory func() (ProjectAPI, error)

type ProjectRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *ProjectCommands) SetRuntime(runtime ProjectRuntime) {
	c.List.runtime = runtime
	c.Create.runtime = runtime
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.Move.runtime = runtime
	c.Delete.runtime = runtime
}

func (c *ProjectCommands) SetFactory(factory ProjectAPIFactory) {
	c.List.factory = factory
	c.Create.factory = factory
	c.Read.factory = factory
	c.Update.factory = factory
	c.Move.factory = factory
	c.Delete.factory = factory
}

type ProjectListCommand struct {
	Request        *string "help:\"プロジェクト一覧のページング・絞り込み条件を含む JSON。直接指定するか @path.json で読み込みます。個別フラグと併用できません。\""
	Page           *int    "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage        *int    "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	Ordering       *string "name:\"ordering\" help:\"任意: 並び順を API の ordering 値で指定します。\""
	IamRole        *string "name:\"iam-role\" help:\"任意: IAM ロール ID で絞り込みます。\""
	ParentFolderID *int    "name:\"parent-folder-id\" help:\"任意: 親フォルダ ID で絞り込みます。\""
	factory        ProjectAPIFactory
	runtime        ProjectRuntime
}

func (c *ProjectListCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Page != nil
	flagsSet = flagsSet || c.PerPage != nil
	flagsSet = flagsSet || c.Ordering != nil
	flagsSet = flagsSet || c.IamRole != nil
	flagsSet = flagsSet || c.ParentFolderID != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &project.ListParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
		}
		if c.Page != nil {
			request.Page = c.Page
		}
		if c.PerPage != nil {
			request.PerPage = c.PerPage
		}
		if c.Ordering != nil {
			value := v1.ListProjectsOrdering(*c.Ordering)
			request.Ordering = &value
		}
		if c.IamRole != nil {
			request.IamRole = c.IamRole
		}
		if c.ParentFolderID != nil {
			request.ParentFolderID = c.ParentFolderID
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ProjectCreateCommand struct {
	Request        *string "help:\"プロジェクトコード、名前、説明を含む JSON。直接指定するか @path.json で読み込みます。コード、名前、説明は必須です。\""
	Code           *string "name:\"code\" help:\"必須: プロジェクトコード。\""
	Name           *string "name:\"name\" help:\"必須: プロジェクト名。\""
	Description    *string "name:\"description\" help:\"必須: プロジェクトの説明。\""
	ParentFolderID *int    "name:\"parent-folder-id\" help:\"任意: 親フォルダ ID。\""
	factory        ProjectAPIFactory
	runtime        ProjectRuntime
}

func (c *ProjectCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Code != nil
	flagsSet = flagsSet || c.Name != nil
	flagsSet = flagsSet || c.Description != nil
	flagsSet = flagsSet || c.ParentFolderID != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &project.CreateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Code == nil {
			return fmt.Errorf("--code が必要です")
		}
		if c.Code != nil {
			request.Code = *c.Code
		}
		if c.Name == nil {
			return fmt.Errorf("--name が必要です")
		}
		if c.Name != nil {
			request.Name = *c.Name
		}
		if c.Description == nil {
			return fmt.Errorf("--description が必要です")
		}
		if c.Description != nil {
			request.Description = *c.Description
		}
		if c.ParentFolderID != nil {
			request.ParentFolderID = c.ParentFolderID
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ProjectReadCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"読み取るプロジェクト ID。\""
	factory ProjectAPIFactory
	runtime ProjectRuntime
}

func (c *ProjectReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ProjectUpdateCommand struct {
	ID          int    "arg:\"\" name:\"id\" help:\"更新するプロジェクト ID。\""
	Name        string "name:\"name\" help:\"更新後のプロジェクト名。\" required:\"\""
	Description string "name:\"description\" help:\"更新後の説明。\" required:\"\""
	factory     ProjectAPIFactory
	runtime     ProjectRuntime
}

func (c *ProjectUpdateCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, c.Name, c.Description)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ProjectMoveCommand struct {
	IDs            []int "name:\"ids\" help:\"移動するプロジェクト ID をカンマ区切りで指定します。\" required:\"\""
	ParentFolderID *int  "name:\"parent-folder-id\" help:\"必須: 移動先フォルダ ID。\" required:\"\""
	factory        ProjectAPIFactory
	runtime        ProjectRuntime
}

func (c *ProjectMoveCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Move(context.Background(), c.IDs, c.ParentFolderID)
}

type ProjectDeleteCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"削除するプロジェクト ID。\""
	factory ProjectAPIFactory
	runtime ProjectRuntime
}

func (c *ProjectDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}
