// Code generated by internal/apigen; DO NOT EDIT.
// API resource: SSO profile.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	sso "github.com/sacloud/sacloud-sdk-go/api/iam/apis/sso"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type SSOCommands struct {
	List   SSOListCommand   "cmd:\"\" help:\"SSO プロファイルを一覧表示します。\""
	Create SSOCreateCommand "cmd:\"\" help:\"SSO プロファイルを作成します。IdP の証明書など複数項目を JSON で指定してください。\""
	Read   SSOReadCommand   "cmd:\"\" help:\"ID を指定して SSO プロファイルを読み取ります。\""
	Update SSOUpdateCommand "cmd:\"\" help:\"SSO プロファイルを更新します。必要な IdP 設定一式を JSON で指定してください。\""
	Delete SSODeleteCommand "cmd:\"\" help:\"ID を指定して SSO プロファイルを削除します。\""
	Link   SSOLinkCommand   "cmd:\"\" help:\"SSO プロファイルを組織にリンクします。\""
	Unlink SSOUnlinkCommand "cmd:\"\" help:\"SSO プロファイルと組織のリンクを解除します。\""
}

type SSOAPI interface {
	List(context.Context, *int, *int) (*v1.ListSsoProfilesOK, error)
	Create(context.Context, sso.CreateParams) (*v1.SSOProfile, error)
	Read(context.Context, int) (*v1.SSOProfile, error)
	Update(context.Context, int, sso.UpdateParams) (*v1.SSOProfile, error)
	Delete(context.Context, int) error
	Link(context.Context, int) (*v1.SSOProfile, error)
	Unlink(context.Context, int) (*v1.SSOProfile, error)
}

type SSOAPIFactory func() (SSOAPI, error)

type SSORuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *SSOCommands) SetRuntime(runtime SSORuntime) {
	c.List.runtime = runtime
	c.Create.runtime = runtime
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
	c.Link.runtime = runtime
	c.Unlink.runtime = runtime
}

func (c *SSOCommands) SetFactory(factory SSOAPIFactory) {
	c.List.factory = factory
	c.Create.factory = factory
	c.Read.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
	c.Link.factory = factory
	c.Unlink.factory = factory
}

type SSOListCommand struct {
	Page    *int "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage *int "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	factory SSOAPIFactory
	runtime SSORuntime
}

func (c *SSOListCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background(), c.Page, c.PerPage)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SSOCreateCommand struct {
	Request *string "help:\"SSO プロファイル作成 JSON（name、description、IdP の entity ID、login/logout URL、X.509 certificate）。直接指定するか @path.json で読み込みます。\""
	factory SSOAPIFactory
	runtime SSORuntime
}

func (c *SSOCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &sso.CreateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SSOReadCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"読み取る SSO プロファイル ID。\""
	factory SSOAPIFactory
	runtime SSORuntime
}

func (c *SSOReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SSOUpdateCommand struct {
	ID      int     "arg:\"\" name:\"id\" help:\"更新する SSO プロファイル ID。\""
	Request *string "help:\"SSO プロファイルの更新 JSON。直接指定するか @path.json で読み込みます。\""
	factory SSOAPIFactory
	runtime SSORuntime
}

func (c *SSOUpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &sso.UpdateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SSODeleteCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"削除する SSO プロファイル ID。\""
	factory SSOAPIFactory
	runtime SSORuntime
}

func (c *SSODeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}

type SSOLinkCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"リンクする SSO プロファイル ID。\""
	factory SSOAPIFactory
	runtime SSORuntime
}

func (c *SSOLinkCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Link(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SSOUnlinkCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"リンクを解除する SSO プロファイル ID。\""
	factory SSOAPIFactory
	runtime SSORuntime
}

func (c *SSOUnlinkCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Unlink(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
