// Code generated by internal/apigen; DO NOT EDIT.
// API resource: ID role.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type IDRoleCommands struct {
	List IDRoleListCommand "cmd:\"\" help:\"利用可能な ID ロールを一覧表示します。\""
	Read IDRoleReadCommand "cmd:\"\" help:\"ID を指定して ID ロールを読み取ります。\""
}

type IDRoleAPI interface {
	List(context.Context, *int, *int) (*v1.ListIdRolesOK, error)
	Read(context.Context, string) (*v1.IdRole, error)
}

type IDRoleAPIFactory func() (IDRoleAPI, error)

type IDRoleRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *IDRoleCommands) SetRuntime(runtime IDRoleRuntime) {
	c.List.runtime = runtime
	c.Read.runtime = runtime
}

func (c *IDRoleCommands) SetFactory(factory IDRoleAPIFactory) {
	c.List.factory = factory
	c.Read.factory = factory
}

type IDRoleListCommand struct {
	Page    *int "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage *int "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	factory IDRoleAPIFactory
	runtime IDRoleRuntime
}

func (c *IDRoleListCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background(), c.Page, c.PerPage)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type IDRoleReadCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"読み取る ID ロール ID。\""
	factory IDRoleAPIFactory
	runtime IDRoleRuntime
}

func (c *IDRoleReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
