// Code generated by internal/apigen; DO NOT EDIT.
// API resource: ID policy.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type IDPolicyCommands struct {
	ReadOrganization   IDPolicyReadOrganizationCommand   "cmd:\"\" help:\"組織の ID ポリシーを参照します。\""
	UpdateOrganization IDPolicyUpdateOrganizationCommand "cmd:\"\" help:\"組織の ID ポリシー全体を置き換えます。変更前に read-organization で現在の設定を保存してください。\""
}

type IDPolicyAPI interface {
	ReadOrganizationIdPolicy(context.Context) ([]v1.IdPolicy, error)
	UpdateOrganizationIdPolicy(context.Context, []v1.IdPolicy) ([]v1.IdPolicy, error)
}

type IDPolicyAPIFactory func() (IDPolicyAPI, error)

type IDPolicyRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *IDPolicyCommands) SetRuntime(runtime IDPolicyRuntime) {
	c.ReadOrganization.runtime = runtime
	c.UpdateOrganization.runtime = runtime
}

func (c *IDPolicyCommands) SetFactory(factory IDPolicyAPIFactory) {
	c.ReadOrganization.factory = factory
	c.UpdateOrganization.factory = factory
}

type IDPolicyReadOrganizationCommand struct {
	factory IDPolicyAPIFactory
	runtime IDPolicyRuntime
}

func (c *IDPolicyReadOrganizationCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadOrganizationIdPolicy(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type IDPolicyUpdateOrganizationCommand struct {
	Request *string "help:\"組織の ID ポリシー全体を表す JSON 配列。直接指定するか @path.json で読み込みます。既存設定全体を置き換えるため、更新前に read-organization で確認してください。\""
	factory IDPolicyAPIFactory
	runtime IDPolicyRuntime
}

func (c *IDPolicyUpdateOrganizationCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &[]v1.IdPolicy{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateOrganizationIdPolicy(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
