// Code generated by internal/apigen; DO NOT EDIT.
// API resource: service principal.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	uuid "github.com/google/uuid"
	serviceprincipal "github.com/sacloud/sacloud-sdk-go/api/iam/apis/serviceprincipal"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type ServicePrincipalCommands struct {
	List       ServicePrincipalListCommand       "cmd:\"\" help:\"サービスプリンシパルを一覧表示します。\""
	Create     ServicePrincipalCreateCommand     "cmd:\"\" help:\"サービスプリンシパルを作成します。\""
	Read       ServicePrincipalReadCommand       "cmd:\"\" help:\"ID を指定してサービスプリンシパルを読み取ります。\""
	Update     ServicePrincipalUpdateCommand     "cmd:\"\" help:\"サービスプリンシパルを更新します。更新後の名前は --name または --request JSON の name に指定してください。\""
	Delete     ServicePrincipalDeleteCommand     "cmd:\"\" help:\"ID を指定してサービスプリンシパルを削除します。\""
	ListKeys   ServicePrincipalListKeysCommand   "cmd:\"\" help:\"サービスプリンシパルに登録されたキーを一覧表示します。\""
	UploadKey  ServicePrincipalUploadKeyCommand  "cmd:\"\" help:\"サービスプリンシパルに PEM 形式の RSA 公開鍵（2048～4096 ビット）を登録します。公開鍵は --public-key-file で読み込みます。\""
	EnableKey  ServicePrincipalEnableKeyCommand  "cmd:\"\" help:\"指定したサービスプリンシパルキーを有効化します。\""
	DisableKey ServicePrincipalDisableKeyCommand "cmd:\"\" help:\"指定したサービスプリンシパルキーを無効化します。\""
	DeleteKey  ServicePrincipalDeleteKeyCommand  "cmd:\"\" help:\"指定したサービスプリンシパルキーを削除します。\""
	IssueToken ServicePrincipalIssueTokenCommand "cmd:\"\" help:\"登録済み公開鍵に対応する秘密鍵で署名した JWT アサーションからアクセストークンを発行します。アサーションは --assertion-file で読み込み、発行されたトークンは秘密情報として扱います。\""
}

type ServicePrincipalAPI interface {
	List(context.Context, serviceprincipal.ListParams) (*v1.ListServicePrincipalsOK, error)
	Create(context.Context, serviceprincipal.CreateParams) (*v1.ServicePrincipal, error)
	Read(context.Context, int) (*v1.ServicePrincipal, error)
	Update(context.Context, int, serviceprincipal.UpdateParams) (*v1.ServicePrincipal, error)
	Delete(context.Context, int) error
	ListKeys(context.Context, int, serviceprincipal.ListKeysParams) (*v1.ListServicePrincipalKeysOK, error)
	UploadKey(context.Context, int, v1.ServiceprincipalKeyPublicKey) (*v1.ServicePrincipalKey, error)
	EnableKey(context.Context, int, uuid.UUID) (*v1.ServicePrincipalKey, error)
	DisableKey(context.Context, int, uuid.UUID) (*v1.ServicePrincipalKey, error)
	DeleteKey(context.Context, int, uuid.UUID) error
	IssueToken(context.Context, string) (*v1.ServicePrincipalOAuth2AccessToken, error)
}

type ServicePrincipalAPIFactory func() (ServicePrincipalAPI, error)

type ServicePrincipalRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *ServicePrincipalCommands) SetRuntime(runtime ServicePrincipalRuntime) {
	c.List.runtime = runtime
	c.Create.runtime = runtime
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
	c.ListKeys.runtime = runtime
	c.UploadKey.runtime = runtime
	c.EnableKey.runtime = runtime
	c.DisableKey.runtime = runtime
	c.DeleteKey.runtime = runtime
	c.IssueToken.runtime = runtime
}

func (c *ServicePrincipalCommands) SetFactory(factory ServicePrincipalAPIFactory) {
	c.List.factory = factory
	c.Create.factory = factory
	c.Read.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
	c.ListKeys.factory = factory
	c.UploadKey.factory = factory
	c.EnableKey.factory = factory
	c.DisableKey.factory = factory
	c.DeleteKey.factory = factory
	c.IssueToken.factory = factory
}

type ServicePrincipalListCommand struct {
	Request   *string "help:\"サービスプリンシパル一覧のページング・絞り込み条件を含む JSON。直接指定するか @path.json で読み込みます。\""
	Page      *int    "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage   *int    "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	ProjectID *int    "name:\"project-id\" help:\"任意: プロジェクト ID で絞り込みます。\""
	Ordering  *string "name:\"ordering\" help:\"任意: 並び順を API の ordering 値で指定します。\""
	factory   ServicePrincipalAPIFactory
	runtime   ServicePrincipalRuntime
}

func (c *ServicePrincipalListCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Page != nil
	flagsSet = flagsSet || c.PerPage != nil
	flagsSet = flagsSet || c.ProjectID != nil
	flagsSet = flagsSet || c.Ordering != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &serviceprincipal.ListParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
		}
		if c.Page != nil {
			request.Page = c.Page
		}
		if c.PerPage != nil {
			request.PerPage = c.PerPage
		}
		if c.ProjectID != nil {
			request.ProjectID = c.ProjectID
		}
		if c.Ordering != nil {
			value := v1.ListServicePrincipalsOrdering(*c.Ordering)
			request.Ordering = &value
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ServicePrincipalCreateCommand struct {
	Request     *string "help:\"サービスプリンシパル作成 JSON。直接指定するか @path.json で読み込みます。\""
	ProjectID   *int    "name:\"project-id\" help:\"必須: 対象プロジェクト ID。\""
	Name        *string "name:\"name\" help:\"必須: サービスプリンシパル名。\""
	Description *string "name:\"description\" help:\"必須: サービスプリンシパルの説明。\""
	factory     ServicePrincipalAPIFactory
	runtime     ServicePrincipalRuntime
}

func (c *ServicePrincipalCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.ProjectID != nil
	flagsSet = flagsSet || c.Name != nil
	flagsSet = flagsSet || c.Description != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &serviceprincipal.CreateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.ProjectID == nil {
			return fmt.Errorf("--project-id が必要です")
		}
		if c.ProjectID != nil {
			request.ProjectID = *c.ProjectID
		}
		if c.Name == nil {
			return fmt.Errorf("--name が必要です")
		}
		if c.Name != nil {
			request.Name = *c.Name
		}
		if c.Description == nil {
			return fmt.Errorf("--description が必要です")
		}
		if c.Description != nil {
			request.Description = *c.Description
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ServicePrincipalReadCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"読み取るサービスプリンシパル ID。\""
	factory ServicePrincipalAPIFactory
	runtime ServicePrincipalRuntime
}

func (c *ServicePrincipalReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ServicePrincipalUpdateCommand struct {
	ID      int     "arg:\"\" name:\"id\" help:\"更新するサービスプリンシパル ID。\""
	Request *string "help:\"更新後の名前を含む JSON。name は必須です。任意の description は JSON で指定できます。直接指定するか @path.json で読み込みます。--request と --name は併用できません。\""
	Name    *string "name:\"name\" help:\"必須: 更新後のサービスプリンシパル名。\""
	factory ServicePrincipalAPIFactory
	runtime ServicePrincipalRuntime
}

func (c *ServicePrincipalUpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Name != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &serviceprincipal.UpdateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Name == nil {
			return fmt.Errorf("--name が必要です")
		}
		if c.Name != nil {
			request.Name = *c.Name
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ServicePrincipalDeleteCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"削除するサービスプリンシパル ID。\""
	factory ServicePrincipalAPIFactory
	runtime ServicePrincipalRuntime
}

func (c *ServicePrincipalDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}

type ServicePrincipalListKeysCommand struct {
	ID       int     "arg:\"\" name:\"id\" help:\"キーを一覧表示するサービスプリンシパル ID。\""
	Request  *string "help:\"キー一覧のページング・並び順条件 JSON。直接指定するか @path.json で読み込みます。--request と個別フラグは併用できません。\""
	Page     *int    "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage  *int    "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	Ordering *string "name:\"ordering\" help:\"任意: 並び順を API の ordering 値で指定します。\""
	factory  ServicePrincipalAPIFactory
	runtime  ServicePrincipalRuntime
}

func (c *ServicePrincipalListKeysCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Page != nil
	flagsSet = flagsSet || c.PerPage != nil
	flagsSet = flagsSet || c.Ordering != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &serviceprincipal.ListKeysParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
		}
		if c.Page != nil {
			request.Page = c.Page
		}
		if c.PerPage != nil {
			request.PerPage = c.PerPage
		}
		if c.Ordering != nil {
			value := v1.ListServicePrincipalKeysOrdering(*c.Ordering)
			request.Ordering = &value
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ListKeys(context.Background(), c.ID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ServicePrincipalEnableKeyCommand struct {
	ID      int       "arg:\"\" name:\"id\" help:\"サービスプリンシパル ID。\""
	KeyID   uuid.UUID "arg:\"\" name:\"key-id\" help:\"有効化するキー ID。\""
	factory ServicePrincipalAPIFactory
	runtime ServicePrincipalRuntime
}

func (c *ServicePrincipalEnableKeyCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.EnableKey(context.Background(), c.ID, c.KeyID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ServicePrincipalDisableKeyCommand struct {
	ID      int       "arg:\"\" name:\"id\" help:\"サービスプリンシパル ID。\""
	KeyID   uuid.UUID "arg:\"\" name:\"key-id\" help:\"無効化するキー ID。\""
	factory ServicePrincipalAPIFactory
	runtime ServicePrincipalRuntime
}

func (c *ServicePrincipalDisableKeyCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.DisableKey(context.Background(), c.ID, c.KeyID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ServicePrincipalDeleteKeyCommand struct {
	ID      int       "arg:\"\" name:\"id\" help:\"サービスプリンシパル ID。\""
	KeyID   uuid.UUID "arg:\"\" name:\"key-id\" help:\"削除するキー ID。\""
	factory ServicePrincipalAPIFactory
	runtime ServicePrincipalRuntime
}

func (c *ServicePrincipalDeleteKeyCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.DeleteKey(context.Background(), c.ID, c.KeyID)
}
