// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM authentication settings.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type AuthCommands struct {
	ReadPasswordPolicy   AuthReadPasswordPolicyCommand   "cmd:\"\" help:\"組織のパスワードポリシーを参照します。\""
	UpdatePasswordPolicy AuthUpdatePasswordPolicyCommand "cmd:\"\" help:\"組織のパスワードポリシーを更新します。--request ではすべての項目を含む JSON を指定します。フラグを使う場合も4項目すべてを指定してください。\""
	ReadAuthConditions   AuthReadConditionsCommand       "cmd:\"\" help:\"組織の認証条件を参照します。\""
	UpdateAuthConditions AuthUpdateConditionsCommand     "cmd:\"\" help:\"組織の認証条件を更新します。現在の設定を read-auth-conditions で確認し、すべての項目を含む JSON を指定してください。\""
	ReadAuthContext      AuthReadContextCommand          "cmd:\"\" help:\"現在の認証情報に対応する IAM 認証コンテキストを参照します。\""
}

type AuthAPI interface {
	ReadPasswordPolicy(context.Context) (*v1.PasswordPolicy, error)
	UpdatePasswordPolicy(context.Context, v1.PasswordPolicy) (*v1.PasswordPolicy, error)
	ReadAuthConditions(context.Context) (*v1.AuthConditions, error)
	UpdateAuthConditions(context.Context, *v1.AuthConditions) (*v1.AuthConditions, error)
	ReadAuthContext(context.Context) (*v1.ReadAuthContextOK, error)
}

type AuthAPIFactory func() (AuthAPI, error)

type AuthRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *AuthCommands) SetRuntime(runtime AuthRuntime) {
	c.ReadPasswordPolicy.runtime = runtime
	c.UpdatePasswordPolicy.runtime = runtime
	c.ReadAuthConditions.runtime = runtime
	c.UpdateAuthConditions.runtime = runtime
	c.ReadAuthContext.runtime = runtime
}

func (c *AuthCommands) SetFactory(factory AuthAPIFactory) {
	c.ReadPasswordPolicy.factory = factory
	c.UpdatePasswordPolicy.factory = factory
	c.ReadAuthConditions.factory = factory
	c.UpdateAuthConditions.factory = factory
	c.ReadAuthContext.factory = factory
}

type AuthReadPasswordPolicyCommand struct {
	factory AuthAPIFactory
	runtime AuthRuntime
}

func (c *AuthReadPasswordPolicyCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadPasswordPolicy(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type AuthUpdatePasswordPolicyCommand struct {
	Request          *string "help:\"パスワードポリシー全体の JSON。直接指定するか @path.json で読み込みます。組織全体の設定を変更するため、更新前に read-password-policy で確認してください。--request と個別フラグは併用できません。\""
	MinLength        *int    "name:\"min-length\" help:\"必須: パスワードの最小文字数。\""
	RequireUppercase *bool   "name:\"require-uppercase\" help:\"必須: 大文字を必須にします。\""
	RequireLowercase *bool   "name:\"require-lowercase\" help:\"必須: 小文字を必須にします。\""
	RequireSymbols   *bool   "name:\"require-symbols\" help:\"必須: 記号を必須にします。\""
	factory          AuthAPIFactory
	runtime          AuthRuntime
}

func (c *AuthUpdatePasswordPolicyCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.MinLength != nil
	flagsSet = flagsSet || c.RequireUppercase != nil
	flagsSet = flagsSet || c.RequireLowercase != nil
	flagsSet = flagsSet || c.RequireSymbols != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &v1.PasswordPolicy{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.MinLength == nil {
			return fmt.Errorf("--min-length が必要です")
		}
		if c.MinLength != nil {
			request.MinLength = *c.MinLength
		}
		if c.RequireUppercase == nil {
			return fmt.Errorf("--require-uppercase が必要です")
		}
		if c.RequireUppercase != nil {
			request.RequireUppercase = *c.RequireUppercase
		}
		if c.RequireLowercase == nil {
			return fmt.Errorf("--require-lowercase が必要です")
		}
		if c.RequireLowercase != nil {
			request.RequireLowercase = *c.RequireLowercase
		}
		if c.RequireSymbols == nil {
			return fmt.Errorf("--require-symbols が必要です")
		}
		if c.RequireSymbols != nil {
			request.RequireSymbols = *c.RequireSymbols
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdatePasswordPolicy(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type AuthReadConditionsCommand struct {
	factory AuthAPIFactory
	runtime AuthRuntime
}

func (c *AuthReadConditionsCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadAuthConditions(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type AuthUpdateConditionsCommand struct {
	Request *string "help:\"認証条件全体の JSON。直接指定するか @path.json で読み込みます。組織全体のログイン条件を変更するため、更新前に read-auth-conditions で確認してください。\""
	factory AuthAPIFactory
	runtime AuthRuntime
}

func (c *AuthUpdateConditionsCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &v1.AuthConditions{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateAuthConditions(context.Background(), request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type AuthReadContextCommand struct {
	factory AuthAPIFactory
	runtime AuthRuntime
}

func (c *AuthReadContextCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadAuthContext(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
