// Code generated by internal/apigen; DO NOT EDIT.
// API resource: SCIM configuration.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	scim "github.com/sacloud/sacloud-sdk-go/api/iam/apis/scim"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type SCIMCommands struct {
	List            SCIMListCommand            "cmd:\"\" help:\"ユーザープロビジョニング設定を一覧表示します。\""
	Create          SCIMCreateCommand          "cmd:\"\" help:\"ユーザープロビジョニング設定を作成します。\""
	Read            SCIMReadCommand            "cmd:\"\" help:\"ID を指定してユーザープロビジョニング設定を読み取ります。\""
	Update          SCIMUpdateCommand          "cmd:\"\" help:\"ユーザープロビジョニング設定を更新します。\""
	Delete          SCIMDeleteCommand          "cmd:\"\" help:\"ID を指定してユーザープロビジョニング設定を削除します。プロビジョニングされたユーザーとグループをすべて削除してから実行してください。\""
	RegenerateToken SCIMRegenerateTokenCommand "cmd:\"\" help:\"ユーザープロビジョニング設定の秘密トークンを再発行します。再発行後は古いトークンが使えなくなるため、連携先を更新できる場合にのみ実行してください。\""
}

type ScimAPI interface {
	List(context.Context, scim.ListParams) (*v1.ListScimConfigurationsOK, error)
	Create(context.Context, scim.CreateParams) (*v1.ScimConfiguration, error)
	Read(context.Context, string) (*v1.ScimConfigurationBase, error)
	Update(context.Context, string, scim.UpdateParams) (*v1.ScimConfigurationBase, error)
	Delete(context.Context, string) error
	RegenerateToken(context.Context, string) (*v1.RegenerateScimConfigurationTokenOK, error)
}

type ScimAPIFactory func() (ScimAPI, error)

type ScimRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *SCIMCommands) SetRuntime(runtime ScimRuntime) {
	c.List.runtime = runtime
	c.Create.runtime = runtime
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
	c.RegenerateToken.runtime = runtime
}

func (c *SCIMCommands) SetFactory(factory ScimAPIFactory) {
	c.List.factory = factory
	c.Create.factory = factory
	c.Read.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
	c.RegenerateToken.factory = factory
}

type SCIMListCommand struct {
	Request *string "help:\"ユーザープロビジョニング設定一覧のページング条件を含む JSON。直接指定するか @path.json で読み込みます。\""
	Page    *int    "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage *int    "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	factory ScimAPIFactory
	runtime ScimRuntime
}

func (c *SCIMListCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Page != nil
	flagsSet = flagsSet || c.PerPage != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &scim.ListParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
		}
		if c.Page != nil {
			request.Page = c.Page
		}
		if c.PerPage != nil {
			request.PerPage = c.PerPage
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SCIMCreateCommand struct {
	Request *string "help:\"ユーザープロビジョニング設定の JSON。name を指定し、直接または @path.json で読み込みます。\""
	Name    *string "name:\"name\" help:\"必須: 設定名。\""
	factory ScimAPIFactory
	runtime ScimRuntime
}

func (c *SCIMCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Name != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &scim.CreateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Name == nil {
			return fmt.Errorf("--name が必要です")
		}
		if c.Name != nil {
			request.Name = *c.Name
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SCIMReadCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"読み取る設定 ID。\""
	factory ScimAPIFactory
	runtime ScimRuntime
}

func (c *SCIMReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SCIMUpdateCommand struct {
	ID      string  "arg:\"\" name:\"id\" help:\"更新する設定 ID。\""
	Request *string "help:\"変更後のユーザープロビジョニング設定を含む JSON。直接指定するか @path.json で読み込みます。\""
	factory ScimAPIFactory
	runtime ScimRuntime
}

func (c *SCIMUpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &scim.UpdateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type SCIMDeleteCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"削除する設定 ID。\""
	factory ScimAPIFactory
	runtime ScimRuntime
}

func (c *SCIMDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}

type SCIMRegenerateTokenCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"トークンを再発行する設定 ID。\""
	factory ScimAPIFactory
	runtime ScimRuntime
}

func (c *SCIMRegenerateTokenCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.RegenerateToken(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
