// Code generated by internal/apigen; DO NOT EDIT.
// API resource: service policy.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	servicepolicy "github.com/sacloud/sacloud-sdk-go/api/iam/apis/servicepolicy"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type ServicePolicyCommands struct {
	Enable            ServicePolicyEnableCommand            "cmd:\"\" help:\"サービス利用ポリシーを有効化します。サービス操作の制限に影響するため、実行前に設定内容を確認してください。\""
	Disable           ServicePolicyDisableCommand           "cmd:\"\" help:\"サービス利用ポリシーを無効化します。サービス操作の制限に影響するため、実行前に設定内容を確認してください。\""
	IsEnabled         ServicePolicyIsEnabledCommand         "cmd:\"\" help:\"サービス利用ポリシーが有効かどうかを確認します。\""
	ListRuleTemplates ServicePolicyListRuleTemplatesCommand "cmd:\"\" help:\"サービス利用ポリシーのルールテンプレートを一覧表示します。\""
}

type ServicePolicyAPI interface {
	Enable(context.Context) error
	Disable(context.Context) error
	IsEnabled(context.Context) (bool, error)
	ListRuleTemplates(context.Context, servicepolicy.ListRuleTemplatesParams) (*v1.ListServicePolicyRuleTemplatesOK, error)
}

type ServicePolicyAPIFactory func() (ServicePolicyAPI, error)

type ServicePolicyRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *ServicePolicyCommands) SetRuntime(runtime ServicePolicyRuntime) {
	c.Enable.runtime = runtime
	c.Disable.runtime = runtime
	c.IsEnabled.runtime = runtime
	c.ListRuleTemplates.runtime = runtime
}

func (c *ServicePolicyCommands) SetFactory(factory ServicePolicyAPIFactory) {
	c.Enable.factory = factory
	c.Disable.factory = factory
	c.IsEnabled.factory = factory
	c.ListRuleTemplates.factory = factory
}

type ServicePolicyEnableCommand struct {
	factory ServicePolicyAPIFactory
	runtime ServicePolicyRuntime
}

func (c *ServicePolicyEnableCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Enable(context.Background())
}

type ServicePolicyDisableCommand struct {
	factory ServicePolicyAPIFactory
	runtime ServicePolicyRuntime
}

func (c *ServicePolicyDisableCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Disable(context.Background())
}

type ServicePolicyIsEnabledCommand struct {
	factory ServicePolicyAPIFactory
	runtime ServicePolicyRuntime
}

func (c *ServicePolicyIsEnabledCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.IsEnabled(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ServicePolicyListRuleTemplatesCommand struct {
	Request *string "help:\"ルールテンプレートの絞り込み条件 JSON。直接指定するか @path.json で読み込みます。\""
	Page    *int    "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage *int    "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	Name    *string "name:\"name\" help:\"任意: 名前で絞り込みます。\""
	Code    *string "name:\"code\" help:\"任意: コードで絞り込みます。\""
	Type    *string "name:\"type\" help:\"任意: 種別で絞り込みます。\""
	factory ServicePolicyAPIFactory
	runtime ServicePolicyRuntime
}

func (c *ServicePolicyListRuleTemplatesCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Page != nil
	flagsSet = flagsSet || c.PerPage != nil
	flagsSet = flagsSet || c.Name != nil
	flagsSet = flagsSet || c.Code != nil
	flagsSet = flagsSet || c.Type != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &servicepolicy.ListRuleTemplatesParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
		}
		if c.Page != nil {
			request.Page = c.Page
		}
		if c.PerPage != nil {
			request.PerPage = c.PerPage
		}
		if c.Name != nil {
			request.Name = c.Name
		}
		if c.Code != nil {
			request.Code = c.Code
		}
		if c.Type != nil {
			value := v1.ListServicePolicyRuleTemplatesType(*c.Type)
			request.Type = &value
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ListRuleTemplates(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
