// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM project API key.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	projectapikey "github.com/sacloud/sacloud-sdk-go/api/iam/apis/projectapikey"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type ProjectAPIKeyCommands struct {
	List   ProjectAPIKeyListCommand   "cmd:\"\" help:\"プロジェクト API キーを一覧表示します。\""
	Create ProjectAPIKeyCreateCommand "cmd:\"\" help:\"プロジェクト API キーを作成します。レスポンスにアクセストークンとシークレットが含まれるため、出力を安全に保管してください。\""
	Read   ProjectAPIKeyReadCommand   "cmd:\"\" help:\"ID を指定してプロジェクト API キーを読み取ります。\""
	Update ProjectAPIKeyUpdateCommand "cmd:\"\" help:\"プロジェクト API キーを更新します。現在の設定を read で確認し、変更後の設定を JSON で指定してください。\""
	Delete ProjectAPIKeyDeleteCommand "cmd:\"\" help:\"ID を指定してプロジェクト API キーを削除します。\""
}

type ProjectAPIKeyAPI interface {
	List(context.Context, projectapikey.ListParams) (*v1.ListApiKeysOK, error)
	Create(context.Context, projectapikey.CreateParams) (*v1.ProjectApiKeyWithSecret, error)
	Read(context.Context, int) (*v1.ProjectApiKey, error)
	Update(context.Context, int, projectapikey.UpdateParams) (*v1.ProjectApiKey, error)
	Delete(context.Context, int) error
}

type ProjectAPIKeyAPIFactory func() (ProjectAPIKeyAPI, error)

type ProjectAPIKeyRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *ProjectAPIKeyCommands) SetRuntime(runtime ProjectAPIKeyRuntime) {
	c.List.runtime = runtime
	c.Create.runtime = runtime
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
}

func (c *ProjectAPIKeyCommands) SetFactory(factory ProjectAPIKeyAPIFactory) {
	c.List.factory = factory
	c.Create.factory = factory
	c.Read.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
}

type ProjectAPIKeyListCommand struct {
	Request  *string "help:\"API キー一覧のページング・並び順条件を含む JSON。直接指定するか @path.json で読み込みます。\""
	Page     *int    "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage  *int    "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	Ordering *string "name:\"ordering\" help:\"任意: 並び順を API の ordering 値で指定します。\""
	factory  ProjectAPIKeyAPIFactory
	runtime  ProjectAPIKeyRuntime
}

func (c *ProjectAPIKeyListCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Page != nil
	flagsSet = flagsSet || c.PerPage != nil
	flagsSet = flagsSet || c.Ordering != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &projectapikey.ListParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
		}
		if c.Page != nil {
			request.Page = c.Page
		}
		if c.PerPage != nil {
			request.PerPage = c.PerPage
		}
		if c.Ordering != nil {
			value := v1.ListApiKeysOrdering(*c.Ordering)
			request.Ordering = &value
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ProjectAPIKeyCreateCommand struct {
	Request *string "help:\"API キー作成リクエスト全体を JSON で指定します。必須の project_id、name、description、IAM ロール配列 iam_roles を含めてください。シングルサーバコントロールパネルで使うキーは server_resource_id と zone_id も指定します（https://manual.sakura.ad.jp/cloud/api/apikey.html）。直接指定するか @path.json で読み込みます。レスポンスには秘密情報（アクセストークンとシークレット）が含まれるため、出力を安全に保管してください。\""
	factory ProjectAPIKeyAPIFactory
	runtime ProjectAPIKeyRuntime
}

func (c *ProjectAPIKeyCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &projectapikey.CreateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ProjectAPIKeyReadCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"読み取る API キー ID。\""
	factory ProjectAPIKeyAPIFactory
	runtime ProjectAPIKeyRuntime
}

func (c *ProjectAPIKeyReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ProjectAPIKeyUpdateCommand struct {
	ID      int     "arg:\"\" name:\"id\" help:\"更新する API キー ID。\""
	Request *string "help:\"変更後の API キー設定全体を含む JSON。直接指定するか @path.json で読み込みます。\""
	factory ProjectAPIKeyAPIFactory
	runtime ProjectAPIKeyRuntime
}

func (c *ProjectAPIKeyUpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &projectapikey.UpdateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type ProjectAPIKeyDeleteCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"削除する API キー ID。\""
	factory ProjectAPIKeyAPIFactory
	runtime ProjectAPIKeyRuntime
}

func (c *ProjectAPIKeyDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}
