// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM user two-factor authentication.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type User2FACommands struct {
	DeactivateOTP       User2FADeactivateOTPCommand       "cmd:\"\" help:\"指定したユーザーの OTP を無効化します。ログイン方法に影響するため、--user-id で対象を確認してください。\""
	ListTrustedDevices  User2FAListTrustedDevicesCommand  "cmd:\"\" help:\"指定したユーザーの信頼済みデバイスを一覧表示します。\""
	DeleteTrustedDevice User2FADeleteTrustedDeviceCommand "cmd:\"\" help:\"指定したユーザーの信頼済みデバイスを削除します。\""
	ClearTrustedDevices User2FAClearTrustedDevicesCommand "cmd:\"\" help:\"指定したユーザーの信頼済みデバイスをすべて削除します。--user-id で対象を確認してください。\""
	ListSecurityKeys    User2FAListSecurityKeysCommand    "cmd:\"\" help:\"指定したユーザーのセキュリティキーを一覧表示します。\""
	ReadSecurityKey     User2FAReadSecurityKeyCommand     "cmd:\"\" help:\"ID を指定してセキュリティキーを読み取ります。\""
	DeleteSecurityKey   User2FADeleteSecurityKeyCommand   "cmd:\"\" help:\"指定したユーザーのセキュリティキーを削除します。\""
}

type User2FAAPI interface {
	DeactivateOTP(context.Context) error
	ListTrustedDevices(context.Context) (*v1.ListTrustedDevicesOK, error)
	DeleteTrustedDevice(context.Context, int) error
	ClearTrustedDevices(context.Context) error
	ListSecurityKeys(context.Context) (*v1.ListSecurityKeysOK, error)
	ReadSecurityKey(context.Context, int) (*v1.UserSecurityKey, error)
	DeleteSecurityKey(context.Context, int) error
}

type User2FAAPIFactory func(UserID int) (User2FAAPI, error)

type User2FARuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *User2FACommands) SetRuntime(runtime User2FARuntime) {
	c.DeactivateOTP.runtime = runtime
	c.ListTrustedDevices.runtime = runtime
	c.DeleteTrustedDevice.runtime = runtime
	c.ClearTrustedDevices.runtime = runtime
	c.ListSecurityKeys.runtime = runtime
	c.ReadSecurityKey.runtime = runtime
	c.DeleteSecurityKey.runtime = runtime
}

func (c *User2FACommands) SetFactory(factory User2FAAPIFactory) {
	c.DeactivateOTP.factory = factory
	c.ListTrustedDevices.factory = factory
	c.DeleteTrustedDevice.factory = factory
	c.ClearTrustedDevices.factory = factory
	c.ListSecurityKeys.factory = factory
	c.ReadSecurityKey.factory = factory
	c.DeleteSecurityKey.factory = factory
}

type User2FADeactivateOTPCommand struct {
	UserID  int "name:\"user-id\" help:\"対象ユーザー ID。操作対象を確認して指定してください。\" required:\"\""
	factory User2FAAPIFactory
	runtime User2FARuntime
}

func (c *User2FADeactivateOTPCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.UserID)
	if err != nil {
		return err
	}
	return op.DeactivateOTP(context.Background())
}

type User2FAListTrustedDevicesCommand struct {
	UserID  int "name:\"user-id\" help:\"対象ユーザー ID。操作対象を確認して指定してください。\" required:\"\""
	factory User2FAAPIFactory
	runtime User2FARuntime
}

func (c *User2FAListTrustedDevicesCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.UserID)
	if err != nil {
		return err
	}
	result, err := op.ListTrustedDevices(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type User2FADeleteTrustedDeviceCommand struct {
	UserID          int "name:\"user-id\" help:\"対象ユーザー ID。操作対象を確認して指定してください。\" required:\"\""
	TrustedDeviceID int "arg:\"\" name:\"trusted-device-id\" help:\"削除する信頼済みデバイス ID。\""
	factory         User2FAAPIFactory
	runtime         User2FARuntime
}

func (c *User2FADeleteTrustedDeviceCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.UserID)
	if err != nil {
		return err
	}
	return op.DeleteTrustedDevice(context.Background(), c.TrustedDeviceID)
}

type User2FAClearTrustedDevicesCommand struct {
	UserID  int "name:\"user-id\" help:\"対象ユーザー ID。操作対象を確認して指定してください。\" required:\"\""
	factory User2FAAPIFactory
	runtime User2FARuntime
}

func (c *User2FAClearTrustedDevicesCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.UserID)
	if err != nil {
		return err
	}
	return op.ClearTrustedDevices(context.Background())
}

type User2FAListSecurityKeysCommand struct {
	UserID  int "name:\"user-id\" help:\"対象ユーザー ID。操作対象を確認して指定してください。\" required:\"\""
	factory User2FAAPIFactory
	runtime User2FARuntime
}

func (c *User2FAListSecurityKeysCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.UserID)
	if err != nil {
		return err
	}
	result, err := op.ListSecurityKeys(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type User2FAReadSecurityKeyCommand struct {
	UserID        int "name:\"user-id\" help:\"対象ユーザー ID。操作対象を確認して指定してください。\" required:\"\""
	SecurityKeyID int "arg:\"\" name:\"security-key-id\" help:\"読み取るセキュリティキー ID。\""
	factory       User2FAAPIFactory
	runtime       User2FARuntime
}

func (c *User2FAReadSecurityKeyCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.UserID)
	if err != nil {
		return err
	}
	result, err := op.ReadSecurityKey(context.Background(), c.SecurityKeyID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type User2FADeleteSecurityKeyCommand struct {
	UserID        int "name:\"user-id\" help:\"対象ユーザー ID。操作対象を確認して指定してください。\" required:\"\""
	SecurityKeyID int "arg:\"\" name:\"security-key-id\" help:\"削除するセキュリティキー ID。\""
	factory       User2FAAPIFactory
	runtime       User2FARuntime
}

func (c *User2FADeleteSecurityKeyCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.UserID)
	if err != nil {
		return err
	}
	return op.DeleteSecurityKey(context.Background(), c.SecurityKeyID)
}
