// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM folder.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	folder "github.com/sacloud/sacloud-sdk-go/api/iam/apis/folder"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type FolderCommands struct {
	List   FolderListCommand   "cmd:\"\" help:\"IAM フォルダを一覧表示します。ページングや絞り込みには --request または対応する個別フラグを指定します。\""
	Create FolderCreateCommand "cmd:\"\" help:\"IAM フォルダを作成します。親フォルダを指定する場合は --parent-id を指定してください。\""
	Read   FolderReadCommand   "cmd:\"\" help:\"ID を指定して IAM フォルダを読み取ります。\""
	Update FolderUpdateCommand "cmd:\"\" help:\"IAM フォルダの名前と説明を更新します。説明を変更しない場合は --description を省略します。\""
	Move   FolderMoveCommand   "cmd:\"\" help:\"指定したフォルダを親フォルダへ移動します。移動先が有効な階層になることを確認してください。\""
	Delete FolderDeleteCommand "cmd:\"\" help:\"ID を指定して IAM フォルダを削除します。\""
}

type FolderAPI interface {
	List(context.Context, folder.ListParams) (*v1.ListFoldersOK, error)
	Create(context.Context, folder.CreateParams) (*v1.Folder, error)
	Read(context.Context, int) (*v1.Folder, error)
	Update(context.Context, int, string, *string) (*v1.Folder, error)
	Move(context.Context, []int, *int) error
	Delete(context.Context, int) error
}

type FolderAPIFactory func() (FolderAPI, error)

type FolderRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *FolderCommands) SetRuntime(runtime FolderRuntime) {
	c.List.runtime = runtime
	c.Create.runtime = runtime
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.Move.runtime = runtime
	c.Delete.runtime = runtime
}

func (c *FolderCommands) SetFactory(factory FolderAPIFactory) {
	c.List.factory = factory
	c.Create.factory = factory
	c.Read.factory = factory
	c.Update.factory = factory
	c.Move.factory = factory
	c.Delete.factory = factory
}

type FolderListCommand struct {
	Request  *string "help:\"folder.ListParams の JSON。直接指定するか @path.json で読み込みます。個別フラグと併用できません。\""
	Page     *int    "name:\"page\" help:\"任意: 取得するページ番号。\""
	PerPage  *int    "name:\"per-page\" help:\"任意: 1 ページあたりの取得件数。\""
	Name     *string "name:\"name\" help:\"任意: 名前で絞り込みます。\""
	ParentID *int    "name:\"parent-id\" help:\"任意: 親フォルダ ID で絞り込みます。\""
	factory  FolderAPIFactory
	runtime  FolderRuntime
}

func (c *FolderListCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Page != nil
	flagsSet = flagsSet || c.PerPage != nil
	flagsSet = flagsSet || c.Name != nil
	flagsSet = flagsSet || c.ParentID != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &folder.ListParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
		}
		if c.Page != nil {
			request.Page = c.Page
		}
		if c.PerPage != nil {
			request.PerPage = c.PerPage
		}
		if c.Name != nil {
			request.Name = c.Name
		}
		if c.ParentID != nil {
			request.ParentID = c.ParentID
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type FolderCreateCommand struct {
	Request     *string "help:\"folder.CreateParams の JSON。名前、説明、任意の親フォルダ ID を指定します。直接指定するか @path.json で読み込みます。\""
	Name        *string "name:\"name\" help:\"必須: フォルダ名。\""
	Description *string "name:\"description\" help:\"任意: フォルダの説明。\""
	ParentID    *int    "name:\"parent-id\" help:\"任意: 親フォルダ ID。\""
	factory     FolderAPIFactory
	runtime     FolderRuntime
}

func (c *FolderCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	flagsSet = flagsSet || c.Name != nil
	flagsSet = flagsSet || c.Description != nil
	flagsSet = flagsSet || c.ParentID != nil
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &folder.CreateParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		if !flagsSet {
			return fmt.Errorf("--request または個別フラグが必要です")
		}
		if c.Name == nil {
			return fmt.Errorf("--name が必要です")
		}
		if c.Name != nil {
			request.Name = *c.Name
		}
		if c.Description != nil {
			request.Description = c.Description
		}
		if c.ParentID != nil {
			request.ParentID = c.ParentID
		}
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type FolderReadCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"読み取るフォルダ ID。\""
	factory FolderAPIFactory
	runtime FolderRuntime
}

func (c *FolderReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type FolderUpdateCommand struct {
	ID          int     "arg:\"\" name:\"id\" help:\"更新するフォルダ ID。\""
	Name        string  "name:\"name\" help:\"必須: 更新後のフォルダ名。\" required:\"\""
	Description *string "name:\"description\" help:\"任意: 更新後の説明。\""
	factory     FolderAPIFactory
	runtime     FolderRuntime
}

func (c *FolderUpdateCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, c.Name, c.Description)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type FolderMoveCommand struct {
	IDs      []int "name:\"ids\" help:\"移動するフォルダ ID をカンマ区切りで指定します。\" required:\"\""
	ParentID *int  "name:\"parent-id\" help:\"必須: 移動先の親フォルダ ID。\" required:\"\""
	factory  FolderAPIFactory
	runtime  FolderRuntime
}

func (c *FolderMoveCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Move(context.Background(), c.IDs, c.ParentID)
}

type FolderDeleteCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"削除するフォルダ ID。\""
	factory FolderAPIFactory
	runtime FolderRuntime
}

func (c *FolderDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}
