// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM organization.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	organization "github.com/sacloud/sacloud-sdk-go/api/iam/apis/organization"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type OrganizationCommands struct {
	Read                OrganizationReadCommand                "cmd:\"\" help:\"IAM 組織の情報を参照します。\""
	Update              OrganizationUpdateCommand              "cmd:\"\" help:\"IAM 組織名を更新します。\""
	ReadServicePolicy   OrganizationReadServicePolicyCommand   "cmd:\"\" help:\"組織のサービス利用ポリシーを参照します。\""
	UpdateServicePolicy OrganizationUpdateServicePolicyCommand "cmd:\"\" help:\"組織のサービス利用ポリシー全体を更新します。変更前に read-service-policy で現在の設定を確認してください。\""
}

type OrganizationAPI interface {
	Read(context.Context) (*v1.Organization, error)
	Update(context.Context, string) (*v1.Organization, error)
	ReadServicePolicy(context.Context, organization.GetServicePolicyParams) ([]v1.RuleResponse, error)
	UpdateServicePolicy(context.Context, []v1.Rule) ([]v1.RuleResponse, error)
}

type OrganizationAPIFactory func() (OrganizationAPI, error)

type OrganizationRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *OrganizationCommands) SetRuntime(runtime OrganizationRuntime) {
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.ReadServicePolicy.runtime = runtime
	c.UpdateServicePolicy.runtime = runtime
}

func (c *OrganizationCommands) SetFactory(factory OrganizationAPIFactory) {
	c.Read.factory = factory
	c.Update.factory = factory
	c.ReadServicePolicy.factory = factory
	c.UpdateServicePolicy.factory = factory
}

type OrganizationReadCommand struct {
	factory OrganizationAPIFactory
	runtime OrganizationRuntime
}

func (c *OrganizationReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type OrganizationUpdateCommand struct {
	Name    string "name:\"name\" help:\"更新後の組織名。\" required:\"\""
	factory OrganizationAPIFactory
	runtime OrganizationRuntime
}

func (c *OrganizationUpdateCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.Name)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type OrganizationReadServicePolicyCommand struct {
	Request *string "help:\"サービス利用ポリシーの絞り込み条件 JSON。省略すると既定の条件で取得します。直接指定するか @path.json で読み込みます。\""
	factory OrganizationAPIFactory
	runtime OrganizationRuntime
}

func (c *OrganizationReadServicePolicyCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &organization.GetServicePolicyParams{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadServicePolicy(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type OrganizationUpdateServicePolicyCommand struct {
	Request *string "help:\"サービス利用ポリシーのルール全体を表す JSON 配列。直接指定するか @path.json で読み込みます。\""
	factory OrganizationAPIFactory
	runtime OrganizationRuntime
}

func (c *OrganizationUpdateServicePolicyCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &[]v1.Rule{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateServicePolicy(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
