// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM policy bindings.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type PolicyCommands struct {
	ReadOrganization   PolicyReadOrganizationCommand   "cmd:\"\" help:\"組織の IAM ポリシーバインディング（ロールとプリンシパルの割り当て）を一覧表示します。\""
	UpdateOrganization PolicyUpdateOrganizationCommand "cmd:\"\" help:\"組織の IAM ポリシーバインディングを置き換えます。現在の割り当て全体を --request に JSON 配列で指定します。read-organization の出力を基に編集してください。\""
	ReadProject        PolicyReadProjectCommand        "cmd:\"\" help:\"指定したプロジェクトの IAM ポリシーバインディング（ロールとプリンシパルの割り当て）を一覧表示します。\""
	UpdateProject      PolicyUpdateProjectCommand      "cmd:\"\" help:\"指定したプロジェクトの IAM ポリシーバインディングを置き換えます。現在の割り当て全体を --request に JSON 配列で指定します。read-project の出力を基に編集してください。\""
	ReadFolder         PolicyReadFolderCommand         "cmd:\"\" help:\"指定したフォルダの IAM ポリシーバインディング（ロールとプリンシパルの割り当て）を一覧表示します。\""
	UpdateFolder       PolicyUpdateFolderCommand       "cmd:\"\" help:\"指定したフォルダの IAM ポリシーバインディングを置き換えます。現在の割り当て全体を --request に JSON 配列で指定します。read-folder の出力を基に編集してください。\""
}

type PolicyAPI interface {
	ReadOrganizationPolicy(context.Context) ([]v1.IamPolicy, error)
	UpdateOrganizationPolicy(context.Context, []v1.IamPolicy) ([]v1.IamPolicy, error)
	ReadProjectPolicy(context.Context, int) ([]v1.IamPolicy, error)
	UpdateProjectPolicy(context.Context, int, []v1.IamPolicy) ([]v1.IamPolicy, error)
	ReadFolderPolicy(context.Context, int) ([]v1.IamPolicy, error)
	UpdateFolderPolicy(context.Context, int, []v1.IamPolicy) ([]v1.IamPolicy, error)
}

type PolicyAPIFactory func() (PolicyAPI, error)

type PolicyRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *PolicyCommands) SetRuntime(runtime PolicyRuntime) {
	c.ReadOrganization.runtime = runtime
	c.UpdateOrganization.runtime = runtime
	c.ReadProject.runtime = runtime
	c.UpdateProject.runtime = runtime
	c.ReadFolder.runtime = runtime
	c.UpdateFolder.runtime = runtime
}

func (c *PolicyCommands) SetFactory(factory PolicyAPIFactory) {
	c.ReadOrganization.factory = factory
	c.UpdateOrganization.factory = factory
	c.ReadProject.factory = factory
	c.UpdateProject.factory = factory
	c.ReadFolder.factory = factory
	c.UpdateFolder.factory = factory
}

type PolicyReadOrganizationCommand struct {
	factory PolicyAPIFactory
	runtime PolicyRuntime
}

func (c *PolicyReadOrganizationCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadOrganizationPolicy(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type PolicyUpdateOrganizationCommand struct {
	Request *string "help:\"現在の割り当ての JSON 配列を直接または @path.json で指定します。各要素は role と principals を持ち、role は type（preset）と id（IAM ロール ID）、principals は type（user など）と id（数値）を指定します。例: --request '[{\\\"role\\\":{\\\"type\\\":\\\"preset\\\",\\\"id\\\":\\\"IAM-ROLE-ID\\\"},\\\"principals\\\":[{\\\"type\\\":\\\"user\\\",\\\"id\\\":123}]}]'\""
	factory PolicyAPIFactory
	runtime PolicyRuntime
}

func (c *PolicyUpdateOrganizationCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &[]v1.IamPolicy{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateOrganizationPolicy(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type PolicyReadProjectCommand struct {
	ProjectID int "arg:\"\" name:\"project-id\" help:\"対象のプロジェクト ID。\""
	factory   PolicyAPIFactory
	runtime   PolicyRuntime
}

func (c *PolicyReadProjectCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadProjectPolicy(context.Background(), c.ProjectID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type PolicyUpdateProjectCommand struct {
	ProjectID int     "arg:\"\" name:\"project-id\" help:\"対象のプロジェクト ID。\""
	Request   *string "help:\"現在の割り当ての JSON 配列を直接または @path.json で指定します。各要素は role と principals を持ち、role は type（preset）と id（IAM ロール ID）、principals は type（user など）と id（数値）を指定します。例: --request '[{\\\"role\\\":{\\\"type\\\":\\\"preset\\\",\\\"id\\\":\\\"IAM-ROLE-ID\\\"},\\\"principals\\\":[{\\\"type\\\":\\\"user\\\",\\\"id\\\":123}]}]'\""
	factory   PolicyAPIFactory
	runtime   PolicyRuntime
}

func (c *PolicyUpdateProjectCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &[]v1.IamPolicy{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateProjectPolicy(context.Background(), c.ProjectID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type PolicyReadFolderCommand struct {
	FolderID int "arg:\"\" name:\"folder-id\" help:\"対象のフォルダ ID。\""
	factory  PolicyAPIFactory
	runtime  PolicyRuntime
}

func (c *PolicyReadFolderCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadFolderPolicy(context.Background(), c.FolderID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type PolicyUpdateFolderCommand struct {
	FolderID int     "arg:\"\" name:\"folder-id\" help:\"対象のフォルダ ID。\""
	Request  *string "help:\"現在の割り当ての JSON 配列を直接または @path.json で指定します。各要素は role と principals を持ち、role は type（preset）と id（IAM ロール ID）、principals は type（user など）と id（数値）を指定します。例: --request '[{\\\"role\\\":{\\\"type\\\":\\\"preset\\\",\\\"id\\\":\\\"IAM-ROLE-ID\\\"},\\\"principals\\\":[{\\\"type\\\":\\\"user\\\",\\\"id\\\":123}]}]'\""
	factory  PolicyAPIFactory
	runtime  PolicyRuntime
}

func (c *PolicyUpdateFolderCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &[]v1.IamPolicy{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateFolderPolicy(context.Background(), c.FolderID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
