// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM group.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	group "github.com/sacloud/sacloud-sdk-go/api/iam/apis/group"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type GroupCommands struct {
	List              GroupListCommand              "cmd:\"\" help:\"IAM グループを一覧表示します。--user-id で指定したユーザーが所属するグループに絞り込めます。\""
	Create            GroupCreateCommand            "cmd:\"\" help:\"IAM グループを作成します。作成後、update-memberships でユーザーを所属させてください。\""
	Read              GroupReadCommand              "cmd:\"\" help:\"ID を指定して IAM グループを読み取ります。\""
	Update            GroupUpdateCommand            "cmd:\"\" help:\"IAM グループの名前と説明を更新します。どちらも必須で、指定しない項目は空で上書きされます。\""
	Delete            GroupDeleteCommand            "cmd:\"\" help:\"ID を指定して IAM グループを削除します。\""
	ReadMemberships   GroupReadMembershipsCommand   "cmd:\"\" help:\"グループに所属するユーザーを一覧表示します。\""
	UpdateMemberships GroupUpdateMembershipsCommand "cmd:\"\" help:\"グループの所属ユーザーを置き換えます。現在の所属は保持されず、指定した配列で上書きされます。read-memberships で現在の所属を確認できます。\""
}

type GroupAPI interface {
	List(context.Context, group.ListParams) ([]v1.Group, error)
	Create(context.Context, string, string) (*v1.Group, error)
	Read(context.Context, int) (*v1.Group, error)
	Update(context.Context, int, string, string) (*v1.Group, error)
	Delete(context.Context, int) error
	ReadMemberships(context.Context, int) ([]v1.GroupMembershipsCompatUsersItem, error)
	UpdateMemberships(context.Context, int, []int) ([]v1.GroupMembershipsCompatUsersItem, error)
}

type GroupAPIFactory func() (GroupAPI, error)

type GroupRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *GroupCommands) SetRuntime(runtime GroupRuntime) {
	c.List.runtime = runtime
	c.Create.runtime = runtime
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
	c.ReadMemberships.runtime = runtime
	c.UpdateMemberships.runtime = runtime
}

func (c *GroupCommands) SetFactory(factory GroupAPIFactory) {
	c.List.factory = factory
	c.Create.factory = factory
	c.Read.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
	c.ReadMemberships.factory = factory
	c.UpdateMemberships.factory = factory
}

type GroupCreateCommand struct {
	Name        string "name:\"name\" help:\"必須: グループ名。\" required:\"\""
	Description string "name:\"description\" help:\"必須: グループの説明。空文字列も指定できます。\" required:\"\""
	factory     GroupAPIFactory
	runtime     GroupRuntime
}

func (c *GroupCreateCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), c.Name, c.Description)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type GroupReadCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"list の出力にあるグループ ID。\""
	factory GroupAPIFactory
	runtime GroupRuntime
}

func (c *GroupReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type GroupUpdateCommand struct {
	ID          int    "arg:\"\" name:\"id\" help:\"更新するグループ ID。\""
	Name        string "name:\"name\" help:\"必須: グループ名。\" required:\"\""
	Description string "name:\"description\" help:\"必須: グループの説明。空文字列も指定できます。\" required:\"\""
	factory     GroupAPIFactory
	runtime     GroupRuntime
}

func (c *GroupUpdateCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, c.Name, c.Description)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type GroupDeleteCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"削除するグループ ID。\""
	factory GroupAPIFactory
	runtime GroupRuntime
}

func (c *GroupDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}

type GroupReadMembershipsCommand struct {
	GroupID int "arg:\"\" name:\"group-id\" help:\"所属ユーザーを確認するグループ ID。\""
	factory GroupAPIFactory
	runtime GroupRuntime
}

func (c *GroupReadMembershipsCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.ReadMemberships(context.Background(), c.GroupID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type GroupUpdateMembershipsCommand struct {
	GroupID int     "arg:\"\" name:\"group-id\" help:\"所属ユーザーを更新するグループ ID。\""
	Request *string "help:\"ユーザー ID の JSON 配列を直接または @path.json で指定します。例: --request '[1,2,3]'\""
	factory GroupAPIFactory
	runtime GroupRuntime
}

func (c *GroupUpdateMembershipsCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &[]int{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.UpdateMemberships(context.Background(), c.GroupID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}
