// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IAM user.

package iamapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	user "github.com/sacloud/sacloud-sdk-go/api/iam/apis/user"
	v1 "github.com/sacloud/sacloud-sdk-go/api/iam/apis/v1"
)

type UserCommands struct {
	List            UserListCommand            "cmd:\"\" help:\"IAM ユーザーを一覧表示します。--page、--per-page、--ordering で取得範囲と並び順を指定できます。\""
	Create          UserCreateCommand          "cmd:\"\" help:\"IAM ユーザーを作成します。パスワードは --password-file でファイルまたは標準入力から指定します。\""
	Read            UserReadCommand            "cmd:\"\" help:\"ID を指定して IAM ユーザーを読み取ります。\""
	Update          UserUpdateCommand          "cmd:\"\" help:\"IAM ユーザーの名前、説明、パスワードを更新します。名前と説明は必須です。パスワードは --password-file を指定した場合のみ変更します。\""
	Delete          UserDeleteCommand          "cmd:\"\" help:\"ID を指定して IAM ユーザーを削除します。\""
	RegisterEmail   UserRegisterEmailCommand   "cmd:\"\" help:\"ユーザーのメールアドレスを登録します。作成時の --email は SSO の外部 IdP ログインで使うメールアドレスで、この操作とは別の項目です。\""
	UnregisterEmail UserUnregisterEmailCommand "cmd:\"\" help:\"ユーザーのメールアドレスの登録を解除します。\""
}

type UserAPI interface {
	List(context.Context, user.ListParams) ([]v1.User, error)
	Create(context.Context, user.CreateParams) (*v1.User, error)
	Read(context.Context, int) (*v1.User, error)
	Update(context.Context, int, user.UpdateParams) (*v1.User, error)
	Delete(context.Context, int) error
	RegisterEmail(context.Context, int, string) error
	UnregisterEmail(context.Context, int) error
}

type UserAPIFactory func() (UserAPI, error)

type UserRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *UserCommands) SetRuntime(runtime UserRuntime) {
	c.List.runtime = runtime
	c.Create.runtime = runtime
	c.Read.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
	c.RegisterEmail.runtime = runtime
	c.UnregisterEmail.runtime = runtime
}

func (c *UserCommands) SetFactory(factory UserAPIFactory) {
	c.List.factory = factory
	c.Create.factory = factory
	c.Read.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
	c.RegisterEmail.factory = factory
	c.UnregisterEmail.factory = factory
}

type UserReadCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"list の出力にあるユーザー ID。\""
	factory UserAPIFactory
	runtime UserRuntime
}

func (c *UserReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type UserDeleteCommand struct {
	ID      int "arg:\"\" name:\"id\" help:\"削除するユーザー ID。\""
	factory UserAPIFactory
	runtime UserRuntime
}

func (c *UserDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}

type UserRegisterEmailCommand struct {
	UserID  int    "arg:\"\" name:\"user-id\" help:\"メールアドレスを登録するユーザー ID。\""
	Email   string "name:\"email\" help:\"必須: 登録するメールアドレス。例: user@example.com\" required:\"\""
	factory UserAPIFactory
	runtime UserRuntime
}

func (c *UserRegisterEmailCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.RegisterEmail(context.Background(), c.UserID, c.Email)
}

type UserUnregisterEmailCommand struct {
	UserID  int "arg:\"\" name:\"user-id\" help:\"メールアドレスの登録を解除するユーザー ID。\""
	factory UserAPIFactory
	runtime UserRuntime
}

func (c *UserUnregisterEmailCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.UnregisterEmail(context.Background(), c.UserID)
}
