// Code generated by internal/apigen; DO NOT EDIT.
// API resource: EventBus process configuration.

package eventbusapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/eventbus/apis/v1"
)

type ProcessConfigurationCommands struct {
	List         ProcessConfigurationListCommand         "cmd:\"\" help:\"実行設定を一覧表示します。例: skr eventbus-api process-configuration list\""
	Read         ProcessConfigurationReadCommand         "cmd:\"\" help:\"ID を指定して実行設定を読み取ります。ID は list の出力で確認できます。\""
	Create       ProcessConfigurationCreateCommand       "cmd:\"\" help:\"実行設定を作成します。実行先サービス（simplenotification、simplemq、autoscale）は先に作成してください。例: skr eventbus-api process-configuration create --request='{\\\"CommonServiceItem\\\":{\\\"Name\\\":\\\"notify\\\",\\\"Settings\\\":{\\\"Destination\\\":\\\"simplenotification\\\",\\\"Parameters\\\":\\\"{\\\\\\\"group_id\\\\\\\":\\\\\\\"GROUP-ID\\\\\\\",\\\\\\\"message\\\\\\\":\\\\\\\"hello\\\\\\\"}\\\"}}}'\""
	Update       ProcessConfigurationUpdateCommand       "cmd:\"\" help:\"実行設定を部分更新します。未指定の項目は変更されません。Settings を指定する場合は Destination と Parameters を含む設定全体を指定してください。\""
	Delete       ProcessConfigurationDeleteCommand       "cmd:\"\" help:\"ID を指定して実行設定を削除します。削除前に対象 ID を確認してください。\""
	UpdateSecret ProcessConfigurationUpdateSecretCommand "cmd:\"\" help:\"実行設定が実行先サービスを呼び出すためのシークレットを登録します。シークレットは --secret-file でファイルまたは標準入力から読み込み、コマンドラインには記述しないでください。SimpleMQ の例: {\\\"APIKey\\\":\\\"SIMPLEMQ-API-KEY\\\"}\""
}

type ProcessConfigurationAPI interface {
	List(context.Context) ([]v1.CommonServiceItem, error)
	Read(context.Context, string) (*v1.CommonServiceItem, error)
	Create(context.Context, v1.CreateCommonServiceItemRequest) (*v1.CommonServiceItem, error)
	Update(context.Context, string, v1.UpdateCommonServiceItemRequest) (*v1.CommonServiceItem, error)
	Delete(context.Context, string) error
	UpdateSecret(context.Context, string, v1.SetSecretRequest) error
}

type ProcessConfigurationAPIFactory func() (ProcessConfigurationAPI, error)

type ProcessConfigurationRuntime struct {
	DecodeRequest   func(string, any) error
	OutputType      func(*kong.Context) (string, error)
	WriteOutput     func(*kong.Context, string, any, ...[]string) error
	ValidateRequest func(string, any) error
}

func (c *ProcessConfigurationCommands) SetRuntime(runtime ProcessConfigurationRuntime) {
	c.List.runtime = runtime
	c.Read.runtime = runtime
	c.Create.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
	c.UpdateSecret.runtime = runtime
}

func (c *ProcessConfigurationCommands) SetFactory(factory ProcessConfigurationAPIFactory) {
	c.List.factory = factory
	c.Read.factory = factory
	c.Create.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
	c.UpdateSecret.factory = factory
}

type ProcessConfigurationListCommand struct {
	factory ProcessConfigurationAPIFactory
	runtime ProcessConfigurationRuntime
}

func (c *ProcessConfigurationListCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type ProcessConfigurationReadCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"list の出力で確認したリソース ID。\""
	factory ProcessConfigurationAPIFactory
	runtime ProcessConfigurationRuntime
}

func (c *ProcessConfigurationReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type ProcessConfigurationCreateCommand struct {
	Request *string "help:\"CommonServiceItem に Name と Settings を含む JSON。直接指定するか @path.json でファイルを指定します。Provider は eventbusprocessconfiguration に自動設定されます。\""
	factory ProcessConfigurationAPIFactory
	runtime ProcessConfigurationRuntime
}

func (c *ProcessConfigurationCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &v1.CreateCommonServiceItemRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("setProcessConfigurationProvider", request); err != nil {
		return err
	}
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type ProcessConfigurationUpdateCommand struct {
	ID      string  "arg:\"\" name:\"id\" help:\"更新する実行設定 ID。\""
	Request *string "help:\"変更する項目を含む UpdateCommonServiceItemRequest JSON。Settings は Destination と Parameters を含む実行設定全体を指定します。直接 JSON または @path.json。Description を null にすると説明を消去します。\""
	factory ProcessConfigurationAPIFactory
	runtime ProcessConfigurationRuntime
}

func (c *ProcessConfigurationUpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &v1.UpdateCommonServiceItemRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type ProcessConfigurationDeleteCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"削除するリソース ID。list の出力で確認できます。\""
	factory ProcessConfigurationAPIFactory
	runtime ProcessConfigurationRuntime
}

func (c *ProcessConfigurationDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}
