// Code generated by internal/apigen; DO NOT EDIT.
// API resource: EventBus schedule.

package eventbusapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/eventbus/apis/v1"
)

type ScheduleCommands struct {
	List   ScheduleListCommand   "cmd:\"\" help:\"スケジュールを一覧表示します。\""
	Read   ScheduleReadCommand   "cmd:\"\" help:\"ID を指定してスケジュールを読み取ります。\""
	Create ScheduleCreateCommand "cmd:\"\" help:\"実行スケジュールを作成します。StartsAt は Unix epoch ミリ秒の整数です。RecurringStep と RecurringUnit（min、hour、day）、または Crontab を指定します。周期は最短 1 分です。例: skr eventbus-api schedule create --request='{\\\"CommonServiceItem\\\":{\\\"Name\\\":\\\"daily\\\",\\\"Settings\\\":{\\\"ProcessConfigurationID\\\":\\\"PROCESS-CONFIGURATION-ID\\\",\\\"StartsAt\\\":1893456000000,\\\"RecurringStep\\\":1,\\\"RecurringUnit\\\":\\\"day\\\"}}}'\""
	Update ScheduleUpdateCommand "cmd:\"\" help:\"スケジュールを部分更新します。未指定項目は変更されません。Settings を更新する場合は ProcessConfigurationID と StartsAt、および周期または Crontab を含めます。\""
	Delete ScheduleDeleteCommand "cmd:\"\" help:\"ID を指定してスケジュールを削除します。削除前に対象 ID を確認してください。\""
}

type ScheduleAPI interface {
	List(context.Context) ([]v1.CommonServiceItem, error)
	Read(context.Context, string) (*v1.CommonServiceItem, error)
	Create(context.Context, v1.CreateCommonServiceItemRequest) (*v1.CommonServiceItem, error)
	Update(context.Context, string, v1.UpdateCommonServiceItemRequest) (*v1.CommonServiceItem, error)
	Delete(context.Context, string) error
}

type ScheduleAPIFactory func() (ScheduleAPI, error)

type ScheduleRuntime struct {
	DecodeRequest   func(string, any) error
	OutputType      func(*kong.Context) (string, error)
	WriteOutput     func(*kong.Context, string, any, ...[]string) error
	ValidateRequest func(string, any) error
}

func (c *ScheduleCommands) SetRuntime(runtime ScheduleRuntime) {
	c.List.runtime = runtime
	c.Read.runtime = runtime
	c.Create.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
}

func (c *ScheduleCommands) SetFactory(factory ScheduleAPIFactory) {
	c.List.factory = factory
	c.Read.factory = factory
	c.Create.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
}

type ScheduleListCommand struct {
	factory ScheduleAPIFactory
	runtime ScheduleRuntime
}

func (c *ScheduleListCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type ScheduleReadCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"list の出力で確認したリソース ID。\""
	factory ScheduleAPIFactory
	runtime ScheduleRuntime
}

func (c *ScheduleReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type ScheduleCreateCommand struct {
	Request *string "help:\"Settings は ProcessConfigurationID、StartsAt（Unix epoch ミリ秒の整数）、RecurringStep と RecurringUnit（min、hour、day）で指定します。RecurringStep/RecurringUnit の代わりに Crontab も指定できます。直接 JSON または @path.json。Provider は eventbusschedule に自動設定されます。\""
	factory ScheduleAPIFactory
	runtime ScheduleRuntime
}

func (c *ScheduleCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &v1.CreateCommonServiceItemRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("setScheduleProvider", request); err != nil {
		return err
	}
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type ScheduleUpdateCommand struct {
	ID      string  "arg:\"\" name:\"id\" help:\"更新するスケジュール ID。\""
	Request *string "help:\"変更する項目を含む UpdateCommonServiceItemRequest JSON。Settings は schedule 用の JSON オブジェクトです。直接 JSON または @path.json。Description を null にすると説明を消去します。\""
	factory ScheduleAPIFactory
	runtime ScheduleRuntime
}

func (c *ScheduleUpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &v1.UpdateCommonServiceItemRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type ScheduleDeleteCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"削除するリソース ID。list の出力で確認できます。\""
	factory ScheduleAPIFactory
	runtime ScheduleRuntime
}

func (c *ScheduleDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}
