// Code generated by internal/apigen; DO NOT EDIT.
// API resource: EventBus trigger.

package eventbusapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	v1 "github.com/sacloud/sacloud-sdk-go/api/eventbus/apis/v1"
)

type TriggerCommands struct {
	List   TriggerListCommand   "cmd:\"\" help:\"トリガーを一覧表示します。\""
	Read   TriggerReadCommand   "cmd:\"\" help:\"ID を指定してトリガーを読み取ります。\""
	Create TriggerCreateCommand "cmd:\"\" help:\"イベントトリガーを作成します。Settings に Source、Types、ProcessConfigurationID を指定します。Source と Types の例示値は実際のイベントソースに置き換えてください。例: skr eventbus-api trigger create --request='{\\\"CommonServiceItem\\\":{\\\"Name\\\":\\\"on-change\\\",\\\"Settings\\\":{\\\"Source\\\":\\\"EVENT-SOURCE\\\",\\\"Types\\\":[\\\"EVENT-TYPE\\\"],\\\"ProcessConfigurationID\\\":\\\"PROCESS-CONFIGURATION-ID\\\"}}}'\""
	Update TriggerUpdateCommand "cmd:\"\" help:\"トリガーを部分更新します。未指定項目は変更されません。Settings を更新する場合は Source、Types、ProcessConfigurationID を含めます。\""
	Delete TriggerDeleteCommand "cmd:\"\" help:\"ID を指定してトリガーを削除します。削除前に対象 ID を確認してください。\""
}

type TriggerAPI interface {
	List(context.Context) ([]v1.CommonServiceItem, error)
	Read(context.Context, string) (*v1.CommonServiceItem, error)
	Create(context.Context, v1.CreateCommonServiceItemRequest) (*v1.CommonServiceItem, error)
	Update(context.Context, string, v1.UpdateCommonServiceItemRequest) (*v1.CommonServiceItem, error)
	Delete(context.Context, string) error
}

type TriggerAPIFactory func() (TriggerAPI, error)

type TriggerRuntime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *TriggerCommands) SetRuntime(runtime TriggerRuntime) {
	c.List.runtime = runtime
	c.Read.runtime = runtime
	c.Create.runtime = runtime
	c.Update.runtime = runtime
	c.Delete.runtime = runtime
}

func (c *TriggerCommands) SetFactory(factory TriggerAPIFactory) {
	c.List.factory = factory
	c.Read.factory = factory
	c.Create.factory = factory
	c.Update.factory = factory
	c.Delete.factory = factory
}

type TriggerListCommand struct {
	factory TriggerAPIFactory
	runtime TriggerRuntime
}

func (c *TriggerListCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type TriggerReadCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"list の出力で確認したリソース ID。\""
	factory TriggerAPIFactory
	runtime TriggerRuntime
}

func (c *TriggerReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type TriggerCreateCommand struct {
	Request *string "help:\"Settings に Source、Types（文字列配列）、ProcessConfigurationID を含む JSON。直接指定するか @path.json でファイルを指定します。Provider は eventbustrigger に自動設定されます。\""
	factory TriggerAPIFactory
	runtime TriggerRuntime
}

func (c *TriggerCreateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &v1.CreateCommonServiceItemRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateRequest == nil {
		return fmt.Errorf("API リクエスト検証が設定されていません")
	}
	if err := c.runtime.ValidateRequest("setTriggerProvider", request); err != nil {
		return err
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Create(context.Background(), *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type TriggerUpdateCommand struct {
	ID      string  "arg:\"\" name:\"id\" help:\"更新するトリガー ID。\""
	Request *string "help:\"変更する項目を含む UpdateCommonServiceItemRequest JSON。Settings は Source、Types、ProcessConfigurationID を含む trigger 用 JSON オブジェクトです。直接 JSON または @path.json。Description を null にすると説明を消去します。\""
	factory TriggerAPIFactory
	runtime TriggerRuntime
}

func (c *TriggerUpdateCommand) Run(ctx *kong.Context) error {
	flagsSet := false
	if c.Request != nil && flagsSet {
		return fmt.Errorf("--request と個別フラグは併用できません")
	}
	request := &v1.UpdateCommonServiceItemRequest{}
	if c.Request != nil {
		if c.runtime.DecodeRequest == nil {
			return fmt.Errorf("API リクエスト処理が設定されていません")
		}
		if err := c.runtime.DecodeRequest(*c.Request, request); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("--request が必要です")
	}
	if c.runtime.ValidateOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	if err := c.runtime.ValidateOutput(ctx); err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Update(context.Background(), c.ID, *request)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, result)
}

type TriggerDeleteCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"削除するリソース ID。list の出力で確認できます。\""
	factory TriggerAPIFactory
	runtime TriggerRuntime
}

func (c *TriggerDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}
