// Code generated by internal/apigen; DO NOT EDIT.
// API resource: IaaS Zone.

package zoneapi

import (
	"context"

	"github.com/alecthomas/kong"
	iaas "github.com/sacloud/sacloud-sdk-go/api/iaas"
	zone "github.com/sacloud/sacloud-sdk-go/service/iaas/zone"
)

type Commands struct {
	Find FindCommand "cmd:\"\" help:\"ゾーン一覧を取得します。名前の抽出例: skr iaas-api zone find --query 'map(.Name)'\""
}

type API interface {
	FindWithContext(context.Context, *zone.FindRequest) ([]*iaas.Zone, error)
}

type APIFactory func() (API, error)

type Runtime struct {
	DecodeRequest   func(string, any) error
	ValidateOutput  func(*kong.Context) error
	WriteOutput     func(*kong.Context, any) error
	ValidateRequest func(string, any) error
}

func (c *Commands) SetRuntime(runtime Runtime) {
	c.Find.runtime = runtime
}

func (c *Commands) SetFactory(factory APIFactory) {
	c.Find.factory = factory
}
