// Code generated by internal/apigen; DO NOT EDIT.
// API resource: SimpleMQ queue.

package simplemqapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	queue "github.com/sacloud/sacloud-sdk-go/api/simplemq/apis/v1/queue"
)

type QueueCommands struct {
	List          QueueListCommand          "cmd:\"\" help:\"キューを一覧表示します。\""
	Read          QueueReadCommand          "cmd:\"\" help:\"ID を指定してキューを読み取ります。\""
	Create        QueueCreateCommand        "cmd:\"\" help:\"キューを作成します。作成後、rotate-api-key でメッセージ API 用のキーを発行してください。\""
	Config        QueueConfigCommand        "cmd:\"\" help:\"キューの設定を更新します。--visibility-timeout-seconds と --expire-seconds を指定するか、--request JSON を指定してください。\""
	Delete        QueueDeleteCommand        "cmd:\"\" help:\"ID を指定してキューを削除します。\""
	CountMessages QueueCountMessagesCommand "cmd:\"\" help:\"キュー内のメッセージ数を取得します。\""
	RotateAPIKey  QueueRotateAPIKeyCommand  "cmd:\"\" help:\"メッセージ API キーを発行または再発行し、結果を出力します。APIKey は認証情報として安全に扱ってください。\""
	ClearMessages QueueClearMessagesCommand "cmd:\"\" help:\"キュー内のメッセージをすべて削除します。\""
}

type QueueAPI interface {
	List(context.Context) ([]queue.CommonServiceItem, error)
	Read(context.Context, string) (*queue.CommonServiceItem, error)
	Create(context.Context, queue.CreateQueueRequest) (*queue.CommonServiceItem, error)
	Config(context.Context, string, queue.ConfigQueueRequest) (*queue.CommonServiceItem, error)
	Delete(context.Context, string) error
	CountMessages(context.Context, string) (int, error)
	RotateAPIKey(context.Context, string) (string, error)
	ClearMessages(context.Context, string) error
}

type QueueAPIFactory func() (QueueAPI, error)

type QueueRuntime struct {
	DecodeRequest   func(string, any) error
	OutputType      func(*kong.Context) (string, error)
	WriteOutput     func(*kong.Context, string, any, ...[]string) error
	ValidateRequest func(string, any) error
}

func (c *QueueCommands) SetRuntime(runtime QueueRuntime) {
	c.List.runtime = runtime
	c.Read.runtime = runtime
	c.Create.runtime = runtime
	c.Config.runtime = runtime
	c.Delete.runtime = runtime
	c.CountMessages.runtime = runtime
	c.RotateAPIKey.runtime = runtime
	c.ClearMessages.runtime = runtime
}

func (c *QueueCommands) SetFactory(factory QueueAPIFactory) {
	c.List.factory = factory
	c.Read.factory = factory
	c.Create.factory = factory
	c.Config.factory = factory
	c.Delete.factory = factory
	c.CountMessages.factory = factory
	c.RotateAPIKey.factory = factory
	c.ClearMessages.factory = factory
}

type QueueListCommand struct {
	factory QueueAPIFactory
	runtime QueueRuntime
}

func (c *QueueListCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.List(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type QueueReadCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"list の出力にあるキュー ID。\""
	factory QueueAPIFactory
	runtime QueueRuntime
}

func (c *QueueReadCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	result, err := op.Read(context.Background(), c.ID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type QueueDeleteCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"削除するキュー ID。\""
	factory QueueAPIFactory
	runtime QueueRuntime
}

func (c *QueueDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.ID)
}

type QueueClearMessagesCommand struct {
	ID      string "arg:\"\" name:\"id\" help:\"メッセージをすべて削除するキュー ID。\""
	factory QueueAPIFactory
	runtime QueueRuntime
}

func (c *QueueClearMessagesCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory()
	if err != nil {
		return err
	}
	return op.ClearMessages(context.Background(), c.ID)
}
