// Code generated by internal/apigen; DO NOT EDIT.
// API resource: SimpleMQ message.

package simplemqapi

import (
	"context"
	"fmt"

	"github.com/alecthomas/kong"
	message "github.com/sacloud/sacloud-sdk-go/api/simplemq/apis/v1/message"
)

type MessageCommands struct {
	Send          MessageSendCommand          "cmd:\"\" help:\"キューへメッセージを送信します。\""
	Receive       MessageReceiveCommand       "cmd:\"\" help:\"キューからメッセージを受信します。\""
	ExtendTimeout MessageExtendTimeoutCommand "cmd:\"\" help:\"受信したメッセージの可視性タイムアウトを延長します。\""
	Delete        MessageDeleteCommand        "cmd:\"\" help:\"受信したメッセージを削除します。\""
}

type MessageAPI interface {
	Send(context.Context, string) (*message.NewMessage, error)
	Receive(context.Context) ([]message.Message, error)
	ExtendTimeout(context.Context, string) (*message.Message, error)
	Delete(context.Context, string) error
}

type MessageAPIFactory func(QueueName string, APIKeyFile string) (MessageAPI, error)

type MessageRuntime struct {
	DecodeRequest   func(string, any) error
	OutputType      func(*kong.Context) (string, error)
	WriteOutput     func(*kong.Context, string, any, ...[]string) error
	ValidateRequest func(string, any) error
}

func (c *MessageCommands) SetRuntime(runtime MessageRuntime) {
	c.Send.runtime = runtime
	c.Receive.runtime = runtime
	c.ExtendTimeout.runtime = runtime
	c.Delete.runtime = runtime
}

func (c *MessageCommands) SetFactory(factory MessageAPIFactory) {
	c.Send.factory = factory
	c.Receive.factory = factory
	c.ExtendTimeout.factory = factory
	c.Delete.factory = factory
}

type MessageSendCommand struct {
	QueueName  string "name:\"queue-name\" help:\"対象キュー名 (5〜64文字の英数字またはハイフン)。\" required:\"\""
	APIKeyFile string "name:\"api-key-file\" help:\"キュー API キーのファイル。キーを直接引数に指定せず、- の場合は標準入力から読み込みます。\" required:\"\""
	Content    string "name:\"content\" help:\"メッセージ本文。API 定義では英数字と + / = の文字で最大256000文字です。\" required:\"\""
	factory    MessageAPIFactory
	runtime    MessageRuntime
}

func (c *MessageSendCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.QueueName, c.APIKeyFile)
	if err != nil {
		return err
	}
	result, err := op.Send(context.Background(), c.Content)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type MessageReceiveCommand struct {
	QueueName  string "name:\"queue-name\" help:\"対象キュー名 (5〜64文字の英数字またはハイフン)。\" required:\"\""
	APIKeyFile string "name:\"api-key-file\" help:\"キュー API キーのファイル。キーを直接引数に指定せず、- の場合は標準入力から読み込みます。\" required:\"\""
	factory    MessageAPIFactory
	runtime    MessageRuntime
}

func (c *MessageReceiveCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.QueueName, c.APIKeyFile)
	if err != nil {
		return err
	}
	result, err := op.Receive(context.Background())
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type MessageExtendTimeoutCommand struct {
	QueueName  string "name:\"queue-name\" help:\"対象キュー名 (5〜64文字の英数字またはハイフン)。\" required:\"\""
	APIKeyFile string "name:\"api-key-file\" help:\"キュー API キーのファイル。キーを直接引数に指定せず、- の場合は標準入力から読み込みます。\" required:\"\""
	MessageID  string "arg:\"\" name:\"message-id\" help:\"receive の出力にあるメッセージ ID。\""
	factory    MessageAPIFactory
	runtime    MessageRuntime
}

func (c *MessageExtendTimeoutCommand) Run(ctx *kong.Context) error {
	if c.runtime.OutputType == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	format, err := c.runtime.OutputType(ctx)
	if err != nil {
		return err
	}
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.QueueName, c.APIKeyFile)
	if err != nil {
		return err
	}
	result, err := op.ExtendTimeout(context.Background(), c.MessageID)
	if err != nil {
		return err
	}
	if c.runtime.WriteOutput == nil {
		return fmt.Errorf("API 出力処理が設定されていません")
	}
	return c.runtime.WriteOutput(ctx, format, result)
}

type MessageDeleteCommand struct {
	QueueName  string "name:\"queue-name\" help:\"対象キュー名 (5〜64文字の英数字またはハイフン)。\" required:\"\""
	APIKeyFile string "name:\"api-key-file\" help:\"キュー API キーのファイル。キーを直接引数に指定せず、- の場合は標準入力から読み込みます。\" required:\"\""
	MessageID  string "arg:\"\" name:\"message-id\" help:\"削除するメッセージ ID。\""
	factory    MessageAPIFactory
	runtime    MessageRuntime
}

func (c *MessageDeleteCommand) Run(ctx *kong.Context) error {
	if c.factory == nil {
		return fmt.Errorf("API クライアントが設定されていません")
	}
	op, err := c.factory(c.QueueName, c.APIKeyFile)
	if err != nil {
		return err
	}
	return op.Delete(context.Background(), c.MessageID)
}
